### ISSUE TITLE
Wrong IPv4 Object returned

### ISSUE THREAD

**Issue by secondnope** [mpenning/ciscoconfparse#102]
The IPv4 object returns wrong values:

**print intf_ip.ip
print intf_ip.ip_object
print intf_ip.network
print intf_ip.network_object**

Currently the output is as followed:

**192.168.211.17
192.168.211.17
192.168.211.16/30
192.168.211.16/30**

From my point of view it should return something like this:

**192.168.211.17
192.168.211.17/30
192.168.211.16
192.168.211.16/30**

Thanks for your support in a advance.

**Comment by mpenning** [comment]
I originally wrote IPv4Obj to return different values than it does now.  The problem is that the current behavior has been the same since at least 2015.  At this point, I'm going to leave things as status-quo.  Unit-tests are current for the relevant IPv4Obj attributes.

```
def testIPv4Obj_attributes():
    ## Ensure that attributes are accessible and pass the smell test
    test_object = IPv4Obj('1.0.0.1 255.255.255.0')
    results_correct = [
        ('ip',            IPv4Address('1.0.0.1')),
        ('ip_object',     IPv4Address('1.0.0.1')),
        ('netmask',       IPv4Address('255.255.255.0')),
        ('prefixlen',     24),
        ('broadcast',     IPv4Address('1.0.0.255')),
        ('network',       IPv4Network('1.0.0.0/24')),
        ('network_object',IPv4Network('1.0.0.0/24')),
        ('hostmask',      IPv4Address('0.0.0.255')),
        ('numhosts',      256),
        ('version',       4),
        ('is_reserved',   False),
        ('is_multicast',  False),
        ('is_private',    False),
        ('as_decimal',    16777217),
        ('as_hex_tuple', ('01', '00', '00', '01')),
        ('as_binary_tuple', ('00000001', '00000000', '00000000', '00000001')),
    ]
    for attribute, result_correct in results_correct:
        assert getattr(test_object, attribute)==result_correct
```
