### ISSUE TITLE
Tests are not packaged

### ISSUE THREAD

**Issue by mcepl** [mpenning/ciscoconfparse#106]
Hi,

I would like to fix packaging for OpenSUSE, but your [release tarball](https://files.pythonhosted.org/packages/5d/1d/9f6052f0b910bd56573bd6e0a3f871d0e432a24504e88befce2b339e403c/ciscoconfparse-1.3.15.tar.gz) does not contain the ``test`` directory. Could you please fix your ``MANIFEST.in`` to have them included in the tarball? Something like the following should help, IMHO.
```diff
matej@hubmaier: ciscoconfparse-1.3.15$ diff -u MANIFEST.in.orig MANIFEST.in
--- MANIFEST.in.orig	2018-01-20 13:00:09.000000000 +0100
+++ MANIFEST.in	2018-05-22 10:46:39.530292143 +0200
@@ -5,5 +5,6 @@
 recursive-exclude * *.orig
 recursive-exclude * BUILD.ME
 recursive-exclude * BITBUCKET_HG
+recursive-include tests
 prune sphinx-doc/_static*
 prune sphinx-doc/_build*
matej@hubmaier: ciscoconfparse-1.3.15$
```

Thank you.

**Comment by mpenning** [comment]
I added recursive-include tests to MANIFEST.in.  Please let me know if you run into more issues.
