### ISSUE TITLE
PyInstaller: IOError: [Errno 2] No such file or directory: with ciscoconfparse library

### ISSUE THREAD

**Issue by kochargs** [mpenning/ciscoconfparse#107]
I created an .exe of my python code using pyinstaller and it was working fine. But after importing this specific package "from ciscoconfparse import CiscoConfParse ", pyinstaller is able to create the .exe but when i execute the .exe it throws an error message

Please see this link for screenshot.
https://i.stack.imgur.com/ajuxd.png

I tried to do the workaround as mentioned in some other posts but none seem to work and this problem is seen only when i use ciscoconfparse module.

Please help how can i get around this problem, it is important to use this module.

**Comment by XenonR** [comment]
Hello kochargs,
I'm no expert in wrapping python into binaries, but first things first.
Is the script working before wrapped to an exe?

From the output alone i speculate that the ciscocinfparse module was not properly included from you wrapper.

But let's see what happens if you run it as native python.

Regards

**Comment by kochargs** [comment]
Hi @XenonR @mpenning 
It works perfect without making it an .exe.
Its only when i create an exe out of it that it stops working with the given error.
I am trying to do this to get around this problem but i am getting another error in doing so

datas=[(  'C:\Python27\Lib\site-packages\ciscoconfparse\version', 'ciscoconfparse' ) ]

The error i get now is

14601 INFO: Appending 'datas' from .spec
Unable to find "C:\Python27\Lib\site-packages\ciscoconfparse♂ersion" when adding binary and data files.

Notice the strange symbol between "ciscoconfparse♂ersion"

**Comment by kochargs** [comment]
Hi @XenonR @mpenning 
It works perfect without making it an .exe.
Its only when i create an exe out of it that it stops working with the given error.
I am trying to do this to get around this problem but i am getting another error in doing so

datas=[(  'C:\Python27\Lib\site-packages\ciscoconfparse\version', 'ciscoconfparse' ) ]

The error i get now is

14601 INFO: Appending 'datas' from .spec
Unable to find "C:\Python27\Lib\site-packages\ciscoconfparse♂ersion" when adding binary and data files.

Notice the strange symbol between "ciscoconfparse♂ersion"

**Comment by XenonR** [comment]
Unfortunately it seems to be a problem with the wrapper then. You should try get support from whoever wrote the wrapper.

My best bet is that `\v` gets interpreted as `ASCII Vertical Tab (VT)`. So try `\\v` instead.

Good luck.

**Comment by kochargs** [comment]
It is working now, what i did was instead of adding ciscoconfparse\version, i added ciscoconfparse* and it did the trick.

datas=[ ( 'C:\Python27\Lib\site-packages\ciscoconfparse*', 'ciscoconfparse' ) ],

This got it working.

**Comment by XenonR** [comment]
Ok, so it really seems the `\v` was the problem. For reference see the table at [String and Bytes literals](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals)

Glad you could solve it.
