### ISSUE TITLE
DeprecationWarning: open() universal newlines mode is deprecated (python 3.5)

### ISSUE THREAD

**Issue by steffenschumacher** [mpenning/ciscoconfparse#114]
Hey, thanks for the cool library.
I'm migrating to python3, and I hit this, which I thought I'd try to fix..
basically for Python3 you just add the extra open() arg: newline=None.
I guess we need to check the python version in order to do this - a bit ugly, but it could be refactored so that the open part precedes the syntax if-statement. The open, read and regex compiling is identical regardless of syntax, so it could be done before checking the syntax flavour?

I'm new to python, so bear with me ;)

**Comment by mpenning** [comment]
Thank you for filing this... I prefer to solve the problem with less `if` statements... I created a method called `openargs()` and used that whenever I called `open()`.  This winds up being a little cleaner. 

The fix is on pypi (version 1.3.20).
