### ISSUE TITLE
ciscoconfparse.py doesn't import under Python3.7.0

### ISSUE THREAD

**Issue by sagarp123** [mpenning/ciscoconfparse#117]
<img width="709" alt="bug" src="https://user-images.githubusercontent.com/17131107/44240501-44a86e00-a173-11e8-8932-2011cb10b9b3.png">

Getting error invalid syntax for this line while executing the code.

**Comment by mpenning** [comment]
> Getting error invalid syntax for this line while executing the code.

- What platform? (Windows 10, Linux, Solaris, etc...)
- What version of python?
- What version of ciscoconfparse?
- How did you install ciscoconfparse?
- What is the exact thing you're doing when you get this error?
- Please update this github issue with the error traceback

**Comment by sagarp123** [comment]
What platform? (Windows 10, Linux, Solaris, etc...) Windows 10
What version of python? 3.7.0
What version of ciscoconfparse? 1.3.20
How did you install ciscoconfparse? pip
What is the exact thing you're doing when you get this error? parsing a config file to print all trunk ports
Please update this github issue with the error traceback

Traceback (most recent call last):
  File "C:/Users/sagarpa/PycharmProjects/Project1/netmiko1.py", line 4, in <module>
    from ciscoconfparse import CiscoConfParse
  File "C:\Users\sagarpa\PycharmProjects\Project1\venv\lib\site-packages\ciscoconfparse\__init__.py", line 1, in <module>
    from .ciscoconfparse import CiscoConfParse
  File "C:\Users\sagarpa\PycharmProjects\Project1\venv\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 5536
    
    ^
SyntaxError: invalid syntax

**Comment by bradh11** [comment]
i am receiving the same error
windows 10
python 3.7.0

error:
Traceback (most recent call last):
  File "asa-extract-obj.py", line 1, in <module>
    from ciscoconfparse import CiscoConfParse
  File "C:\python\lib\site-packages\ciscoconfparse\__init__.py", line 1, in <module>
    from .ciscoconfparse import *
  File "C:\python\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 5536

    ^
SyntaxError: invalid syntax

**Comment by bradh11** [comment]
i just confirmed it is happening with all lines which are split using the "\".

**Comment by bradh11** [comment]
for example in ccp_util.py:
                return (self.network<=val.network) and \

                    (self.broadcast>=val.broadcast)

if i change to a single line as follows, the error goes away:
                return (self.network<=val.network) and (self.broadcast>=val.broadcast)

**Comment by mpenning** [comment]
Python 3.7 is not tested or supported right now; I can confirm that something changed about Python3.7, but I don't know what yet.

I also confirmed that I can "pip3.exe install -U ciscoconfparse" and there is no issue with Python3.6 under Windows.  Please download Python3.6.x from python.org:

https://www.python.org/downloads/windows/

**Comment by sagarp123** [comment]
It is working fine with Python 3.6.x.

Thank you.

**Comment by konaya** [comment]
Perhaps this should be mentioned in the README, which currently states in two places that Python 3.2+ is supported.

**Comment by bogd** [comment]
I am seeing the same issue under a fresh install of Python 3.7.0, under Windows 10 x64; ciscoconfparse was installed using pip.

It seems that during download, something (pip?) adds a new, empty, line after every single line of code in the .py files (the sshot in the original issue report shows this very nicely). While this is not a problem for most lines, it does cause errors on lines that were split using '\'.

I have managed to fix this manually by removing the empty lines in the ciscoconfparse files (in lib\site-packages\ciscoconfparse).

Amazingly, not all of the files have been affected. Some of them (like protocol_values.py, or models_asa.py) were OK. Others, however (ciscoconfparse.py, models_cisco.py, models_nxos.py, ccp_abc.py, ccp_util.py, etc) were exhibiting the issue.

**Comment by mpenning** [comment]
I just downloaded Python3.7.1 on x64 (Windows 10), then ran pip3 install -U ciscoconfparse.  I had no problems with 3.7.1.

Please note: Before I installed 3.7.1, I completely uninstalled *and deleted* the original Python 3.7.0 windows directory.  In my case, Python3.7 was installed in "C:\Users\mpenning\AppData\Local\Programs\Python\Python37".

Please try uninstalling Python 3.7.0, delete the residual directories, then reinstall with Python 3.7.1.

**Comment by chiragvyas50** [comment]
> i just confirmed it is happening with all lines which are split using the "\".

Fresh installation did not work for me. Removing "\" from couple of files worked for me

I tried 3.7.0, 3.7.1, 3.7.2

**Comment by chiragvyas50** [comment]
> for example in ccp_util.py:
> ` return (self.network<=val.network) and \
> 
> ```
>                 (self.broadcast>=val.broadcast)`
> ```
> if i change to a single line as follows, the error goes away:
> `return (self.network<=val.network) and (self.broadcast>=val.broadcast)`

Fresh installation did not work for me. Removing "/" from couple of files worked for me

I tried 3.7.0, 3.7.1, 3.7.2

**Comment by mpenning** [comment]
I installed Python for Windows x64 version 3.7.2...

I still cannot reproduce the problems you're asking about...

![image](https://user-images.githubusercontent.com/36991/53289341-86395780-375a-11e9-9403-dbf59d5bb453.png)

**Comment by chiragvyas50** [comment]
@mpenning 
Surprisingly, even i am not able to reproduce it.
This time it not giving any error for the below syntax
`return (self.network<=val.network) and \
                    (self.broadcast>=val.broadcast)`
Last time it was not liking this ' \ ' multi line syntax. When i removed the multi line and put it in single line it was working.
Anyways, now i think it is working with multi line as well. So, i would say i am good. Thank you very much to look into it.
