### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by konaya** [mpenning/ciscoconfparse#119]
The link http://www.pennington.net/py/ciscoconfparse/ in the README is broken; thus, there is no documentation to be had.

**Comment by mpenning** [comment]
I don't see a problem with the hyperlink

![image](https://user-images.githubusercontent.com/36991/46141319-38efa300-c219-11e8-8cb2-4f6b2aee520c.png)

**Comment by konaya** [comment]
Interesting. The authoritative DNS servers for that domain are _really slow,_ making things time out if you're using an intermediary DNS server. You might want to look into that.
