### ISSUE TITLE
re_match_iter_typed() attempts to cast default return value

### ISSUE THREAD

**Issue by jrschneider** [mpenning/ciscoconfparse#121]
When parsing an interface line in a Cisco configuration:

`line.re_match_iter_typed(r'^\s*switchport access vlan (\d+)', result_type=int, default=None)`

If the regex provided does not match one of the children, the default value (None in the case above) is cast (incorrectly IMO) to an int:

```
Traceback (most recent call last):
  File "bin/cni/cutsheet.py", line 268, in <module>
    cisco_switch_port_dict[port_id] = {'access_vlan': line.re_match_iter_typed(r'^\s*switchport access vlan (\d+)', result_type=int, default=None) }
  File "/home/disturbedmime/.virtualenvs/cpp-py3/lib/python3.5/site-packages/ciscoconfparse/ccp_abc.py", line 648, in re_match_iter_typed
    return result_type(default)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
I would think that the default return value in the case of no match would not be subject to casting? If you want a static int() default, it should be set as part of default=....

ciscoconfparse==1.3.20
Python 3.5.2

**Comment by jrschneider** [comment]
I'm aware that for this particular line that I'm matching that `IOSIntfLine.access_vlan` exists, but I have several other lines in this config that I'm matching in this fashion that do not have similar shortcut attributes.

**Comment by mpenning** [comment]
> I would think that the default return value in the case of no match would not be
>  subject to casting?

I agree in principle; however, I don't want to change the behavior now because people might be depending on it.

I will introduce a boolean argument called `untyped_default` (defaullt: False) which could be set True if you don't want the default value to be typed.

**Comment by mpenning** [comment]
Version 1.3.21 incorporates the ```untyped_default``` keyword... please set it true if you don't want the default return value to be typed.

Explicitly in your example:
```line.re_match_iter_typed(r'^\s*switchport access vlan (\d+)', result_type=int, untyped_default=True, default=None)```
