### ISSUE TITLE
Python wheel install broke while running Python 2.7

### ISSUE THREAD

**Issue by FossilBlade** [mpenning/ciscoconfparse#129]
Hey There,

Thanks for the wonderful lib. Its is awesome. How ever it seems that the latest version is not compatible with Python 2.7.5 as it gives the following error:

``` 
Traceback (most recent call last):
  File "test_config.py", line 627, in <module>
    from ios_config_parser import CISCO8194G
  File "/home/raush/vsts_git/PyCharmProjects/Test_conf_parser_2.7/ios_config_parser/CISCO8194G.py", line 1, in <module>
    from ciscoconfparse import CiscoConfParse
  File "/usr/lib/python2.7/site-packages/ciscoconfparse/__init__.py", line 1, in <module>
    from .ciscoconfparse import *
  File "/usr/lib/python2.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 11, in <module>
    from .models_cisco import IOSHostnameLine, IOSRouteLine, IOSIntfLine
  File "/usr/lib/python2.7/site-packages/ciscoconfparse/models_cisco.py", line 11, in <module>
    from .ccp_abc import BaseCfgLine
  File "/usr/lib/python2.7/site-packages/ciscoconfparse/ccp_abc.py", line 37
    class BaseCfgLine(object, metaclass=ABCMeta):
                                       ^
SyntaxError: invalid syntax
 ```

**Comment by mpenning** [comment]
Hello @FossilBlade 

There seems to be something wrong.  I don't know what version of ciscoconfparse that you're using, but the error quoting "class BaseCfgLine(object, metaclass=ABCMeta):" doesn't match any recent version of ciscoconfparse that I know of.

Please don't simply take my word for it... observe it in the repo yourself:
https://github.com/mpenning/ciscoconfparse/blob/master/ciscoconfparse/ccp_abc.py#L37

As such, please consider running "pip install -U ciscoconfparse" (as root) to ensure that you have the latest version installed

**Comment by TheBirdsNest** [comment]
I also have this issue running CCP version 1.3.27 (I have run "pip install -U ciscoconfparse")

```
root@f699c840de44:/app/# pip install -U ciscoconfparse
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: ciscoconfparse in /usr/local/lib/python2.7/site-packages (1.3.27)
Requirement already satisfied, skipping upgrade: passlib in /usr/local/lib/python2.7/site-packages (from ciscoconfparse) (1.7.1)
Requirement already satisfied, skipping upgrade: dnspython in /usr/local/lib/python2.7/site-packages (from ciscoconfparse) (1.16.0)
Requirement already satisfied, skipping upgrade: ipaddr>=2.1.11; python_version < "3" in /usr/local/lib/python2.7/site-packages (from ciscoconfparse) (2.2.0)
Requirement already satisfied, skipping upgrade: colorama in /usr/local/lib/python2.7/site-packages (from ciscoconfparse) (0.4.1)
root@f699c840de44:/app/# python
Python 2.7.15 (default, Sep  5 2018, 04:46:44)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ciscoconfparse/__init__.py", line 1, in <module>
    from .ciscoconfparse import *
  File "/usr/local/lib/python2.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 11, in <module>
    from .models_cisco import IOSHostnameLine, IOSRouteLine, IOSIntfLine
  File "/usr/local/lib/python2.7/site-packages/ciscoconfparse/models_cisco.py", line 11, in <module>
    from .ccp_abc import BaseCfgLine
  File "/usr/local/lib/python2.7/site-packages/ciscoconfparse/ccp_abc.py", line 37
    class BaseCfgLine(object, metaclass=ABCMeta):
                                       ^
SyntaxError: invalid syntax
>>>
```

**Comment by surculus12** [comment]
@mpenning The code inside the [current wheel on PyPi](https://files.pythonhosted.org/packages/63/f4/89b2ee174c065a0bd99ff5ef826db3f0495c96a7400572b6bcee6c0da6fd/ciscoconfparse-1.3.27-py2.py3-none-any.whl) is wrong. (`sha 18370cb3f6c265e829b3f49a3d741bc57f9780a0c8a8c8b8a2ecffb87a2f817c`). The [corresponding tarball](https://files.pythonhosted.org/packages/c9/9c/78b816d60705d4672477085ecce1b9ac9f3f5dae7eca78518f4206e74731/ciscoconfparse-1.3.27.tar.gz) seems to have the right code.

Probably best to rebuild the package as 1.3.28. In the meantime manually installing the package or downgrading to 1.3.26 resolves the issue.

Do you know how it got downstream? The diffs shows mostly python 2 -> 3 syntax changes.

**Comment by mpenning** [comment]
I reproduced the problem with ccp_abc.py.  I configured 1.3.27 with:

```
[bdist_wheel]
universal = 1
```

Before this I used ```universal = 0```; I'm guessing the universal boolean is what broke Python2 wheel packaging.  I will try to fix the problem over the weekend of 9 Feb 2019.

**Comment by mpenning** [comment]
For now, I stopped building universal wheels again.  I tested 1.3.28 under both Python2.7 and Python3.6 virtual envs and observed no ill affects.

I double-checked that wheels (in this case, only a Python2 wheel) install correctly by manually downloading the wheel and checking the contents for problems.

**Comment by surculus12** [comment]
Awesome, thanks for the quick response and explanation!
