### ISSUE TITLE
ASA config: find_objects_w_child(): why is the wrong parent object returned?

### ISSUE THREAD

**Issue by danielarapi** [mpenning/ciscoconfparse#138]
Device: Cisco ASA 
All running-configs are saved to the variable **`config`.** 
I am trying to **`use find_objects_w_child()`** to search for any parent that has a child with the keyword **`nat`** in it

regex for parentspec = r"^\w"
regex for childspec = r"^\s+.*nat"

```
 for item in configs.find_objects_w_child(r"^\w", r"^\s+.*nat.*"):
    print(item) 
```

Output:

```
<IOSCfgLine # 52 'banner motd           WARNING: Use of this system is Restricted and Monitored!'>
<IOSCfgLine # 70 'banner motd     Firm policy, your improper or unauthorized use of this system may result' (parent is # 69)>
<IOSCfgLine # 112 'object network obj_any' (parent is # 70)>
```

----

It should be returning` object network obj_any` as the parent of `nat (inside,outside) dynamic interface`
```
object network obj_any
 nat (inside,outside) dynamic interface
```

It should be returning

**Comment by danielarapi** [comment]
Temporary workaround to this is to use the following regex that skips banner configs:

for item in configs.find_objects_w_child(r"^(?!banner)^\w", r"^\s+.*nat.*"):
    print(item)

**Comment by mpenning** [comment]
Please add an ASA config which can be used to reproduce this problem... it doesn't need to be big

**Comment by mpenning** [comment]
I'm going to go out on a limb and guess that you parsed your ASA config like this: ```parse = CiscoConfParse(config_lines)```.

ASA configs must be parsed like this: ```parse = CiscoConfParse(config_lines, syntax='asa')```
