### ISSUE TITLE
Parsing brace delimited configurations does not preserve line numbers

### ISSUE THREAD

**Issue by CameronNemo** [mpenning/ciscoconfparse#142]
The IOSCfgLine objects report the wrong line numbers when using junos syntax. Perhaps a `!` could be added in place of a `}` delimiter so that the configuration line numbers are preserved.

**Comment by mpenning** [comment]
Have you considered checking how the line numbers match up when you use `ignore_blank_lines=False`?

Example:
```python
parse = CiscoConfParse(CONFIG, syntax='junos', ignore_blank_lines=False)
```

**Comment by CameronNemo** [comment]
I have not, will do in ~48 hours.

**Comment by CameronNemo** [comment]
Well I gave it a shot and the line numbers are same as before. There are no blank lines in my config.

**Comment by mpenning** [comment]
if you want me to investigate further please either email me or attach the
config to this GitHub issue.

**Comment by CameronNemo** [comment]
You can clearly notice the issue with a simple configuration:

```
system {
    services {
        dhcp
    }
    syslog {
        console
    }
}
```

```
>>> from ciscoconfparse import CiscoConfParse as ccp
>>> conf = ccp(lines, syntax='junos', comment='#!', ignore_blank_lines=False)
>>> conf
<CiscoConfParse: 5 lines / syntax: junos / comment delimiter: '#!' / factory: False>
>>> for line in conf.find_objects(r'.*'):
...     print(line)
...
<IOSCfgLine # 0 'system '>
<IOSCfgLine # 1 '    services ' (parent is # 0)>
<IOSCfgLine # 2 '        dhcp' (parent is # 1)>
<IOSCfgLine # 3 '    syslog ' (parent is # 0)>
<IOSCfgLine # 4 '        console' (parent is # 3)>
```

Notice how syslog and console are off by one line (corresponding to the single closing brace in the services section). Replacing that closing brace with a comment character while parsing the configuration could alleviate the issue.

**Comment by mpenning** [comment]
what version of ciscoconfparse are you using?

**Comment by CameronNemo** [comment]
```
ciscoconfparse==1.3.33
colorama==0.4.1
dnspython==1.16.0
passlib==1.7.1
```

**Comment by mpenning** [comment]
I adjusted Junos parsing behavior in version 1.3.36.  Please update ciscoconfparse with `pip3`, I believe you'll see blank lines now.

**Comment by CameronNemo** [comment]
Thanks, all good now.
