### ISSUE TITLE
Find Cisco IOS Macro blocks

### ISSUE THREAD

**Issue by BradSteffen** [mpenning/ciscoconfparse#143]
Hello and thank you for making a fantastic tool!

I have a need to find and delete macro blocks inside IOS configurations.

Unfortunately Cisco does not indent the child lines inside the macro so the normal child logic will not work.  However all macros do start with a "macro name" line and do end with an "@" alone on a line. 

A nice summary of IOS macros can be found here:  
https://ccie-or-null.net/2011/06/13/working-with-cisco-macros/

Thank you again,

- Brad

**Comment by mpenning** [comment]
Support for parsing IOS macros should be live in version 1.3.34.  Please let me know if you find issues with macro support.

**Comment by BradSteffen** [comment]
Hi Mike:

Thank you for turning this around so quickly.

Under 1.3.34, CiscoConfParse(filename) can no longer open configuration files that include macro statements.  The exception returned is "list index out of range". 

Traceback (most recent call last):
  File "nfv-conversion-cisco-rtr-config.py", line 183, in procConfigFile
    confParse = CiscoConfParse(workingFilePath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 234, in __init__
    CiscoConfParse=self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 2503, in __init__
    self._list = self._bootstrap_obj_init(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 2835, in _bootstrap_obj_init
    self._macro_mark_children(macro_parent_idx_list) # Process macros
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 2726, in _macro_mark_children
    cobj = self._list[idx]
IndexError: list index out of range

Configuration files that do not include macros still open correctly.  

Thank you again for your help!

- Brad

**Comment by mpenning** [comment]
Hello Brad,

Please attach the problem config so I can reproduce the problem.

**Comment by BradSteffen** [comment]
Hi Mike:
I will need to sanitize a config and then make sure it still fails in the same way. I will see what I can do in the next day or so. 

Thank you, 

- Brad

**Comment by BradSteffen** [comment]
Hi Mike:
I was able to strip down the config file to just the macro block and the CiscoConfParse(filename) import still fails with the same Traceback as above.

The stripped down config file chunk is attached here:
[macro.txt](https://github.com/mpenning/ciscoconfparse/files/3099756/macro.txt)

Thank you for your attention and help!

- Brad

**Comment by mpenning** [comment]
Hello Brad,

I just pushed 1.3.35 to pypi and github.  FWIW, the only macro statements I'm paying attention to are: "macro name FOO".  I am not doing anything (yet) with "macro global description".

**Comment by BradSteffen** [comment]
Hi Mike:
1.3.35 works perfectly.

Thank you again for the quick turn on these changes!

- Brad
