### ISSUE TITLE
Line Numbers Aren't Matching Up

### ISSUE THREAD

**Issue by clay584** [mpenning/ciscoconfparse#147]
$pip freeze | grep conf
    ciscoconfparse==1.3.39

When looking for configs, the line numbers are not always lining up to what is in the real config file. I have tried `ignore_blank_lines=False` as well, and they still don't line up.

    lines_w_telnet = [i.linenum for i in config.find_objects(r"transport input (telnet ssh|ssh telnet|telnet)")]

returns `[281, 286, 291, 296]`

but the real line numbers are `[284, 289, 294, 299]`

If I remove all of the blank lines in the config, it is still one line off.

**Comment by mpenning** [comment]
Please add your config so I can reproduce

**Comment by clay584** [comment]
After a little more research, it appears that there are two lines in the original config that ciscoconfparse disregards and are not present after parsing occurs, even with ignore_blank_lines=False.

The original file contains two lines following the banner motd message, but before the ending banner delimiter. In this config file, the delimeter is `^C`.
```
================================================================================
================================================================================



!
line con 0
```

Once parsed, ciscoconfparse shows two less lines than the original config file. I have validated that the original config shows 303 lines with wc, gedit, and sublime text.

Doing the math, if these two lines are counted correctly, then everything lines up fine.

I sent you an email with the anonymized configuration to your email address listed on your www.pennington.net website.

**Comment by clay584** [comment]
I think I know the source of the issue. One line 107 of ciscoconfparse.py, your regex for finding end of lines is `\r*\n+` and works fine, unless the next line in the text file is a ASCII control character (or maybe some other non-printable characters). This causes that regex to not match for the line before the line with the control character. Thus also, not selecting the line with the control character as well. This gives us the deficit of the two lines.

This regex seems to match it and works fine `linesplit_rgx=r"(?:\r*\n+|\003+)"`, but I am not sure if it has any negative repercussions elsewhere in the code.

**Comment by mpenning** [comment]
How did the control character get into the configuration?  If this was Cisco IOS, it is a bug.  I can't support changing ciscoconfparse because of a bug (either in your capture method or IOS)

**Comment by clay584** [comment]
The person that made the configuration used `^C` as the banner's delimiter. It's not a bug, it's just a choice that was made by the operator. Technically it's the correct control char delimiter to use. It signals end-of-text.

**Comment by mpenning** [comment]
I took a look at the configuration you emailed me... You just need to supply a different parameter to `CiscoConfParse()` when you process the configuration.

Specifically, parse it like this:
`parse = CiscoConfParse('anon.txt', linesplit_rgx=r'')`

The reason I included a `linesplit_rgx` parameter is so users can split lines however they like.  That's a user-supplied parameter... you don't need to accept the default value.

**Comment by clay584** [comment]
When I parse with the blank line at the top, it does not appear to ignore it ([shows first line captured](https://imgur.com/a/a9Mzaz1)). Which is good for my use-case. I would argue that setting `ignore_blank_lines=False` should not ignore any lines in a config file, not even the first line of a file. If you were to do that, it wouldn't be very truthy (or falsy), but it would be doing something in the middle.

I guess this is what happens when I try to debug code at 2:00am, I don't realize that I can set `linesplit_rgx` parameter to whatever I need. Now I can just look for this one-off case and correct for it.

With `linesplit_rgx=r"(?:\r*\n+|\003+)"` and `ignore_blank_lines=False`, everything is working for me.

Thanks for taking the time to respond and help me out with this.

**Comment by clay584** [comment]
Just posting the solution in case anyone else runs up on this.

For my code, making a test-case for banner delimiters that are any of the standard ASCII control codes and parsing differently with ciscoconfparse.

```
re_ctrl_char_pattern = regex.compile(r'^banner\s+\S+\s+[\001\002\003\004\005\006\007\010\011\012\013\014\015\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037]')
has_ctrl_char = False
for line in self.text.splitlines():
    match = regex.search(re_ctrl_char_pattern, line)
    if match:
        has_ctrl_char = True

# Parse differently if it has a control char in it
if has_ctrl_char:
    self.parsed_config = CiscoConfParse(self.filename, ignore_blank_lines=False, linesplit_rgx=r"(?:\r*\n+|[\001\002\003\004\005\006\007\010\011\012\013\014\015\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037])")
else:
    self.parsed_config = CiscoConfParse(self.filename, ignore_blank_lines=False)
```
