### ISSUE TITLE
Multiple children with same prefix not available with find_objects_w_child

### ISSUE THREAD

**Issue by cclouse** [mpenning/ciscoconfparse#149]
Parsing a Cisco CallManager Express (CME) configuration.  When looking at the raw data, only number 1 is available.  Additional numbers for multiple lines on a phone are not displaying.

sippools = parse.find_objects_w_child("voice register pool", "id mac")

voice register pool  1
 busy-trigger-per-button 2
 id mac AAAA.BBBB>CCCC
 type 8811
 number 1 dn 1
 number 2 dn 2
 dialplan 1
 dtmf-relay rtp-nte sip-notify
 voice-class codec 1
 username user1 password 12345
 conference drop-mode local
 conference add-mode creator
 conference admin
!
voice register dn  1
 number 1234
 call-forward b2bua busy 4321
 call-forward b2bua noan 4321 timeout 20
 name User 1
 label User 1
 mwi
!
voice register dn  2
 number 1235
 call-forward b2bua busy 4321
 call-forward b2bua noan 4321 timeout 20
 name User 2
 label User 2
 mwi

**Comment by mpenning** [comment]
Based solely on the information above `sippools = parse.find_objects_w_child("voice register pool", "id mac")` can only match one parent: `voice register pool 1`.

If there is a problem with a larger configuration, please include that (with a monospace font) so I can see the parents and children in question.

**Comment by cclouse** [comment]
We are only looking to match a single parent pool, but it could potentially match multiple children with the same “number” tag.

voice register pool  1
busy-trigger-per-button 2
id mac DDDD.EEEE.FFFF
type 8811
number 1 dn 1 <-- indicates line 1 on Cisco Phone
number 2 dn 2 <--indicates line 2 on Cisco Phone
dialplan 1
dtmf-relay rtp-nte sip-notify
voice-class codec 1
username user1 password 12345
conference drop-mode local
conference add-mode creator
conference admin
!

~Chris

**Comment by mpenning** [comment]
`find_objects_w_child()` was not supposed to find multiple values (or children) beneath it.  If you want to do something like this, consider this example from the tutorial in the docs:

http://pennington.net/py/ciscoconfparse/tutorial_get_config_values.html#getting-multiple-values-from-an-interface-with-re-match-typed
