### ISSUE TITLE
Print Parent Interface Descriptions

### ISSUE THREAD

**Issue by jab375** [mpenning/ciscoconfparse#150]
Can CiscoConfparse grab the interface descriptions once list of interfaces is built base on the code below? I cant find the documentation that explains this feature or do I need to use another file parse tool?

NoDot1x = parse.find_objects_wo_child(r'^interface', r'authentication')

**Comment by mpenning** [comment]
This is one way to fill the requirements:

```python
# parse configuration here
intf_descr_dict = dict()
NoDot1x = parse.find_objects_wo_child(r'^interface', r'authentication')
for obj in NoDot1x:
    descr = obj.re_match_iter_typed('^\s+description\s+(\S.+)$', default='')
    print obj, descr
    intf_descr_dict[obj] = descr

# etc...
```
