### ISSUE TITLE
Multiple Interface Matching when they should not

### ISSUE THREAD

**Issue by jab375** [mpenning/ciscoconfparse#151]
I have an issue where 9/1 9/10 9/11-19 are matching in my DESC = xxx. Is there a way to limit the find_childern_w_parents to search only for the exact port name in my ports variable and not 9/1*?

`for ports in final_list:
         print(host + ports) 
         desc = parse.find_children_w_parents(ports,'description')
         if desc:
               result = host +'   ' + ''.join(ports)+'   '+ ''.join(desc)
               print(result)
`

**Comment by mpenning** [comment]
Please see Question 5 in the FAQ... I believe it will solve your problem.


https://github.com/mpenning/ciscoconfparse/
