### ISSUE TITLE
HSRP syntax for NXOS model

### ISSUE THREAD

**Issue by steffenschumacher** [mpenning/ciscoconfparse#152]
Hi,
It seems the config syntax from ios have been copy-pasted to nxos - can you confirm this?
If so, I guess I might work on a pull request for it to be supported?

**Comment by mpenning** [comment]
@steffenschumacher the functionality in models_nxos.py and models_cisco.py are listed as beta... as such, noone should be surprised if something doesn't work or isn't supported.

That said, I changed NXOS HSRP to have more support in 1.3.41, which is on pypi now.
