### ISSUE TITLE
comma missing between parameters

### ISSUE THREAD

**Issue by matthew-jolley** [mpenning/ciscoconfparse#153]
https://github.com/mpenning/ciscoconfparse/blob/3a7827432230bd3a44a4675ac95e9c5238433112/ciscoconfparse/models_nxos.py#L1434

**Comment by mpenning** [comment]
Hello and thank you for reporting the problem.

I pushed version 1.3.41 to pypi just before I went to work and noticed the
problem after I got to work.

I will fix it tonight; apologies for the inconvenience.

**Comment by mpenning** [comment]
This should be fixed in version 1.3.42
