### ISSUE TITLE
SyntaxError: from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by svde** [mpenning/ciscoconfparse#154]
Recently the rpm package for ciscoconfparse fails to build with this error:

`[  133s]   File "/usr/lib/python2.7/site-packages/ciscoconfparse/__main__.py", line 4
[  133s] SyntaxError: from __future__ imports must occur at the beginning of the file`

See [link](https://build.opensuse.org/package/live_build_log/home:stefan_van_der_eijk/python-ciscoconfparse/Fedora_30/x86_64)

**Comment by mpenning** [comment]
I'm going to take a swing at fixing this for you, but you should investigate what your ciscoconfparse rpm build process is doing that `pip install ciscoconfparse` does not.  I can think of no reason that you need `__main__.py` in an rpm build script.

**Comment by svde** [comment]
1.3.43 fixed it. Thanks!
