### ISSUE TITLE
Support a 'root' CfgLine object

### ISSUE THREAD

**Issue by CameronNemo** [mpenning/ciscoconfparse#156]
This line would have as its children all other top level lines in the configuration, a dummy line number, and an empty/concealed hierarchy (i.e. it would not show up in other lines' hierarchy).

The advantage is that I can use the same processing mechanisms for top level config lines as subordinate lines, rather than switching between two incompatible object types constantly.

**Comment by CameronNemo** [comment]
For now I am working around this by wrapping both re_search_children and find_objects in a single function:

```python
def search_children(conf, pattern):
    if isinstance(conf, IOSCfgLine):
        return conf.re_search_children(r'^\s*{}\s*$'.format(pattern))
    elif isinstance(conf, CiscoConfParse):
        return conf.find_objects(r'^{}\s*$'.format(pattern), exactmatch=True)
    else:
        assert False
```

**Comment by mpenning** [comment]
I would like to know more about your use-case such that the `conf` argument above in `search_children()` could somehow be a CiscoConfParse instance or an IOSCfgLine instance.  I have been using the library for years myself, and such a problem never even comes up for me...

**Comment by CameronNemo** [comment]
Hi Michael, thank you for your reply. The concrete use case I have in mind is checking JunOS configurations, which have a dense hierarchy. As a simple example, I look for the `system > ports > console > disable` directive, where `>` represents another layer of hierarchy. To accomplish dense traversals like this efficiently, I have implemented a function which descends a tree passed and root object to use as the parent.

Without `search_children()` I first have to call the `find_objects()` method on the `CiscoConfParse` object, then pass the line to my traversal function to search through the rest of the tree.

```python
conf = CiscoConfParse(...)
return list(map(
    lambda x: traverse(x, ('ports', 'console', 'disable'),
    conf.find_objects('^system\s*$', exactmatch=True)
))
```

If the traversal function uses `search_children()`, I can just pass the CCP object directly.

```python
conf = CiscoConfParse(...)
return traverse(conf, ('system', 'ports', 'console', 'disable'))
```

The top level line (for 'system') can be derived from the CCP object, and the traversal function can transparently abstract the difference away so the actual business logic is less complicated.

**Comment by mpenning** [comment]
I added a keyword to `find_objects_w_all_children()` in version 1.4.0, which may assist with what you're trying to do.

Please check whether this does what you want...

```
parse.find_objects_w_all_children('system', ['ports', 'console', 'disable'],
    recurse=True)
```

**Comment by CameronNemo** [comment]
That breaks apart in this case:

```
system {
	ports {
		console {
			XXX;
		}
		auxiliary {
			disable;
		}
	}
}
```

Furthermore my traversal function supports arbitrary combinations of lists and tuples, so logic such as `traverse(conf, ('system', 'ports', [('console', 'disable'), ('auxiliary', 'insecure')]))` is possible.

**Comment by mpenning** [comment]
In general, it's better to ask for an API, than try to dictate how someone implements it.  In this case, I am not ready to implement and maintain the code for a new root object, as requested in this issue.

However, I implemented `re_search_children()` directly on the CiscoConfParse() object.  Perhaps this will help.  Please use version 1.4.1 to get this new method.

**Comment by mpenning** [comment]
@CameronNemo I revisited this issue while I was documenting another method and realized that [find_object_branches()](http://www.pennington.net/py/ciscoconfparse/api_CiscoConfParse.html?highlight=find_object_branches#ciscoconfparse.CiscoConfParse.find_object_branches "find_object_branches()") may be a useful addition for you.
