### ISSUE TITLE
NXOS HSRP Issue with has_ip_hsrp function

### ISSUE THREAD

**Issue by ysi** [mpenning/ciscoconfparse#158]
Hi, 

I used ciscoconfparse for parsing a NXOS config.
On a interface which has no hsrp config but have a IP address, the script crash.

Here the config of vlan that I attempt to parse

interface Vlan1500
  no shutdown
  description MgmtInBand-HDI
  ip address 10.154.242.253/25

Here the crash log

  File "/lib/python2.7/site-packages/ciscoconfparse/models_nxos.py", line 1283, in has_ip_hsrp
    return bool(self.hsrp_ip_addr)
  File "/lib/python2.7/site-packages/ciscoconfparse/models_nxos.py", line 1302, in hsrp_ip_addr
    return retval
UnboundLocalError: local variable 'retval' referenced before assignment

**Comment by mpenning** [comment]
This should be fixed in version 1.4.0
