### ISSUE TITLE
Radware config parse problem, children as parent instead of children

### ISSUE THREAD

**Issue by i-m-d** [mpenning/ciscoconfparse#163]
Hello,

 I am trying to parse Radware balancer config, but the config though it is almost parent/child config, some children start the config as a parent, so this is the problem:

 <IOSCfgLine # 12074 '/c/slb/virt 770'>,
 <IOSCfgLine # 12078 '/c/slb/virt 770/service 110 pop3'>,
 <IOSCfgLine # 12081 '/c/slb/virt 770/service 995 basic-slb'>,
 <IOSCfgLine # 12084 '/c/slb/virt 770/service 143 imap'>,
 <IOSCfgLine # 12087 '/c/slb/virt 770/service 993 basic-slb'>,
 <IOSCfgLine # 12090 '/c/slb/virt 770/service 2000 basic-slb'>,
 <IOSCfgLine # 12093 '/c/slb/virt 770/service 4190 basic-slb'>,
 <IOSCfgLine # 12096 '/c/slb/virt 770/service 24 basic-slb'>,

Here ALL are parents, but really only the first is parent and the rest are children of that parent.

NOTE: the real parent and his children, ALL, have children.

Any trick, CiscoConfParse upgrade o similar to parse this kind of configs ?

Thank you in advance.

**Comment by mpenning** [comment]
> Any trick, CiscoConfParse upgrade o similar to parse this kind of configs ?

CiscoConfParse does not support Radware configurations.
