### ISSUE TITLE
BaseNXOSIntfLine doesn't have dhcp relay address property

### ISSUE THREAD

**Issue by noziwatele** [mpenning/ciscoconfparse#165]
This is probably a Feature Req.

I'm using CiscoConfParse 1.4.5 on NXOS configs, using find_interface_objects(), and I see that the NXOSIntfLine doesn't come with 'has_ip_dhcp_relay' or 'ip_dhcp_relay_addresses' properties. This would be nice to have.

Here's a sample config, in case you need it:

```
interface Vlan7
  vrf member VRF-NAME
  no ip redirects
  ip address 10.1.1.2/24
  ip unreachables
  hsrp version 2
  hsrp 1
    preempt
    priority 120
    ip 10.1.1.1
  ip dhcp relay address 172.16.1.2
  ip dhcp relay address 172.16.2.2
  ip dhcp relay address 10.2.1.9
  ip dhcp relay address 10.2.1.13
  description INT-DESCRIPTION
  no shutdown

```

Cheers!

**Comment by mpenning** [comment]
This is supported in version 1.4.7
