### ISSUE TITLE
Accept pathlib Path objects as file paths

### ISSUE THREAD

**Issue by Gunni** [mpenning/ciscoconfparse#169]
Not much more to say, was trying to understand why I got an exception loading any file...

```
Traceback (most recent call last):
  File "./check.py", line 38, in <module>
    parse = ccp(entry, debug=True, factory=True)
  File "/root/PRJTASK0119300/venv/lib64/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 300, in __init__
    " an invalid argument\n")
RuntimeError: [FATAL] CiscoConfParse() received an invalid argument
```

In the end, it was because `config` in that scope had type `pathlib.PosixPath` which your code wasn't expecting.

**Comment by mpenning** [comment]
Up until now, parsing `pathlib` objects was not supported; however, I attempted to add support in version 1.4..10... please test and advise whether this meets your needs.
