### ISSUE TITLE
Ignores Excludes Regex syntax

### ISSUE THREAD

**Issue by jm7647** [mpenning/ciscoconfparse#175]
By definition Python allows exclusions:

         [^ab5] | Adding ^ excludes any character in the set

From my experience I can't exclude anything using CiscoConfParse.

**Comment by mpenning** [comment]
Please consider altering your negative regex...  I think this does what you want:

```python
>>> from ciscoconfparse import CiscoConfParse

>>> parse = CiscoConfParse(['thing 1', 'thing 3', 'thing 5'])
>>> parse.find_objects(r'^[^ab5]+$')  # When excluding characters you need to match the line
[<IOSCfgLine # 0 'thing 1'>, <IOSCfgLine # 1 'thing 3'>]
