### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 36214: invalid continuation byte

### ISSUE THREAD

**Issue by network-shark** [mpenning/ciscoconfparse#176]
Hello @mpenning , 

thank your for building this cool library. While using it I came across a device config which seems to have a strange character inside. I'm not familiar with encoding , but for me the configurations looks completely normal , but not for python.

I could reproduce it via the python interactive console , if I print it out line by line it breaks with 

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 36214: invalid continuation byte
```
```
  File "/home/XXXX/.pyenv/versions/py376/lib/python3.7/site-packages/ciscoconfparse/ciscoconfparse.py", lin
e 230, in __init__
    text = f.read()

```
Stackoverflow helped me to get it working within the python console , if I switch the encoding to ISO-8859-1 everything works fine. 

Could that be implemented in your read statement ? I think that would fix it .

**Comment by mpenning** [comment]
@network-shark , please either attach a hyperlink to the file you're trying to parse or email the file to me (penningtonthing@gmail.com).

**Comment by network-shark** [comment]
Thanks for the fast response , I could nail it down to the following snmp statement which has the town "Pécs" inside. 

My workaround at the moment is to use  iconv -f ISO-8859-1 -t UTF-8 input > output , which works fine , but mabye you would support those type of characters.

**Comment by mpenning** [comment]
When someone submits a full config for this problem, we can reconsider this request; as of now, there doesn't seem to be enough to continue
