### ISSUE TITLE
find_all_children is returning empty when linespec has a "+"

### ISSUE THREAD

**Issue by lazarim** [mpenning/ciscoconfparse#179]
When the parent name has a "+" in the name the find_all_children is not catching it. 
The same is happening with find_children.

Example:
 class_map_children = parse.find_all_children('INGRESS+CORE-POLICY', exactmatch=False)
 print(class_map_children)

Returns an empty list although it exists in the configuration file.
[]

Am running Python 3.8.3, but saw the same behaviour with 3.6. 
It seemed to be working with Python 2.7.10

**Comment by mpenning** [comment]
You should use a raw string with an escaped plus sign.  Without escaping the plus, it gets interpreted as a regular expression element.

```python
from ciscoconfparse import CiscoConfParse

CONFIG = """policy-map INGRESS+CORE-policy
 class FOO
"""
parse = CiscoConfParse(CONFIG.splitlines())
class_map_children = parse.find_all_children(r'INGRESS\+CORE-policy', exactmatch=False)
print("OUT "+str(class_map_children))
```

The output is:
```
OUT ['policy-map INGRESS+CORE-policy', ' class FOO']
```

**Comment by lazarim** [comment]
Sorry for not getting back on this. You were correct and that was my problem.

Thank you
