### ISSUE TITLE
ciscoconfparse is very slow for large configuration file (3L lines) for alcatel 

### ISSUE THREAD

**Issue by Velu09** [mpenning/ciscoconfparse#182]
I am using cisconfparse for alcatel sros configuration file which is having around 3 lac lines.
It is very slow and taking around 25 to 27 mins for creating configobj and executing other functions( find_parents_w_children,find_all_children).
Please suggest me to optimize the run time.

**Comment by mpenning** [comment]
Hello,

Is there any way you can send your alcatel config and your script which uses ciscoconfparse?

If you like, send me a personal email (optionally encrypt your attachments) with the aforementioned details: penningtonthing@gmail.com

**Comment by mpenning** [comment]
Closing... no response
