### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by shakur2222** [mpenning/ciscoconfparse#198]
Having issues with running the example in the tutorial. pretty new t python so it is most likly user error but from what i can tell its all installed correctly. any help is appreciated 

```python
from ciscoconfparse import CiscoConfParse

# Parse the config into objects
parse = CiscoConfParse('config.txt, syntax='ios')

# Iterate over all the interface objects
for intf_obj in parse.find_objects('^interface'):
    print("ciscoconfparse object: " + intf_obj)
```

PS C:\Users\xxx
  File "c:\Users\xxx, line 4
    parse = CiscoConfParse('config.txt, syntax='ios')
                                                                          ^
SyntaxError: invalid syntax

**Comment by shakur2222** [comment]
formatted very wrong. the "^" is supposed to be under ios then i get the syntaxError. Thanks

**Comment by mpenning** [comment]
Hello @shakur2222 

Your quotes around `config.txt` are not correct... this will fix it...

```python
parse = CiscoConfParse('config.txt', syntax='ios')
```
