### ISSUE TITLE
py2.7 not supported by loguru

### ISSUE THREAD

**Issue by KGalea** [mpenning/ciscoconfparse#201]
Ciscoconfparse says it supports py2.7, however it has just added loguru to requirements without a specified version and the latest version of loguru only supports py3, so venv fails.

**Comment by mpenning** [comment]
We no longer support py2.7...  if you must have py2.7 support, then feel free to install verison 1.5.30

**Comment by KGalea** [comment]
Py2.7 is still mentioned on pypi, maybe the comment under pre-reqs at https://pypi.org/project/ciscoconfparse/#id1 should be removed?
btw, thank you for a fantastic library :)
