### ISSUE TITLE
setup command: use_2to3 is invalid for setuptools > 58

### ISSUE THREAD

**Issue by parth-dj** [mpenning/ciscoconfparse#205]
It looks like setuptools>=58 breaks support for use_2to3.

https://setuptools.pypa.io/en/latest/history.html#v58-0-0

Can we disable / not use _use_2to3_ in the setup parameters?

**Comment by harshita01398** [comment]
Seeing the same issue for this package with latest setuptools. Can we please have a fix?

**Comment by mpenning** [comment]
> Can we please have a fix?

It's time to retire setuptools.  Doing this is more complicated than average because I built custom tooling around my setuptools workflow.

In the mean time, fall back to a manual workaround... 

```shell
# Get a copy of the repo, downloading a github tarball works just as well as `git clone`
git clone git@github.com:mpenning/ciscoconfparse
cd ciscoconfparse
pip install ciscoconfparse
```

**Comment by parth-dj** [comment]
You should consider fixing it as pinning the 'setuptools' dependency will usually start causing more dependency issues as other packages update. It can only be a temporary solution. 
May be create a separate version for older Win systems? (which made you use "use_2to3"?)

**Comment by mpenning** [comment]
> May be create a separate version for older Win systems? (which made you use "use_2to3"?)

👎

**Comment by mpenning** [comment]
Thank you for your patience; this issue should be resolved.  Please use version 1.6.6 for the latest updates and fixes.
