### ISSUE TITLE
Issue when parsing IOS-XR configs with more than 3 levels of config

### ISSUE THREAD

**Issue by ethanroy** [mpenning/ciscoconfparse#21]
Hey, I am having some issues parsing through some config to pull route targets out of IOS-XR config, after working with it for a while it seems like any config with 4 indents doesn't get evaluated.

Config:
![screen shot 2015-02-10 at 10 56 47 am](https://cloud.githubusercontent.com/assets/9750284/6131721/8b2e35d4-b113-11e4-90e4-bf0b5c6ed62e.png)

Script:
![screen shot 2015-02-10 at 10 57 47 am](https://cloud.githubusercontent.com/assets/9750284/6131748/c7f8b8a4-b113-11e4-96a2-2e62a3406d3f.png)

Output:
node$ python vrf.py
['vrf test', ' address-family ipv4 unicast', '  import route-policy bgp-pref', '  import route-target', '  export route-target']

Let me know what you think, everything else I have done has worked great.
Thanks

**Comment by mpenning** [comment]
Thank you for reporting this problem. The bug should be fixed in version 1.2.10; I added a unit test to detect the issue going forward.
