### ISSUE TITLE
Problems sharing the Loguru logger after 1.5.48

### ISSUE THREAD

**Issue by kace** [mpenning/ciscoconfparse#211]
Hi mpenning,

I'm using ciscoconfparse as a dep of [napalm](https://github.com/napalm-automation/napalm). In the same app I'm also using the [Loguru](https://github.com/Delgan/loguru). This seems to be a conflict that  results in `BlockingIOError`'s and eventually `OSError`'s for every logging call in my app (my services writes logs to a file). 

It looks like my logging configuration is removed by the `logger.remove()` call in https://github.com/mpenning/ciscoconfparse/commit/72dcc02d164be22c8c0f4d8aa454dec89a67af18 on line 138 after I import napalm and ciscoconfparse by extension. I was wondering if the logger configuration be changed so that it could be shared?

FYI I also opened an issue on the Loguru project in the hopes of getting more feedback on how to handle this conflict - https://github.com/Delgan/loguru/issues/534. I've included the logger errors on that issue.

Thanks for your effort on ciscoconfparse!

**Comment by mpenning** [comment]
@kace I pushed v1.6.0 to master and pypi.

Take a look and advise whether the ciscoconfparse changes to loguru.logger() usage fix the problem you've hit.

**Comment by kace** [comment]
Hi mpenning,

Thanks for the quick turn around. Unfortunately the changes in v1.6.0 didn't help the issue. 

On my side I was exploring the possibility of using a separate copy logger following this [recipe](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers) but haven't had any luck with it. This might be have to do with the Loguru logger being some sort of singleton object that's instantiated at import time - meaning changing the import name or making a copy of it might not make any difference. It might even have to do with the way that Loguru wraps around the stdlib logging module, but honestly I haven't investigated looked at the internals of Loguru yet. I'm hoping we can get some input on this from the Loguru dev before I resort to that.

Thanks again for the effort and keep me updated if you happen to try anything else I'm happy to perform tests. I'll keep you updated on my side.

**Comment by mpenning** [comment]
I will build an argument to disable logging… thank you for bearing with me on this matter.

**Comment by kace** [comment]
No worries, I'm relieved just to getting any sort of engagement/support!

**Comment by mpenning** [comment]
> By the way I'm curious if what you're imagining is an optional argument on the `CiscoConfParse` object? That'd mean that I'd need to monkey patch [napalm](https://github.com/napalm-automation/napalm) to set it, but that shouldn't be a big deal.

I don't understand why monkey patching napalm is the first choice... if it was me, I'd just ensure that napalm's [`requirements.txt`](https://github.com/napalm-automation/napalm/blob/develop/requirements.txt) requires version 1.6.0 or later

**Comment by mpenning** [comment]
@kace please test and advise whether or not your ccp logging problems are solved... If possible, disable ccp_logger before configuring your own loguru logger.

**Comment by kace** [comment]
Hi mpenning,

Ah you're right there's no need for monkey patching using this method to disable the ccp logger. I just tested v1.6.4 and everything seems to work as expected. 

I'll continue to follow up with the Loguru dev in the hopes of figuring out a cleaner solution to this problem. I'll update you if anything changes on that side, but you can consider my issue with `ciscoconfparse` fixed in your latest release.

Thanks again!
