### ISSUE TITLE
ciscoconfparse hangs during import due to loguru logger conflict with gevent / celery

### ISSUE THREAD

**Issue by TomaszKrassowski** [mpenning/ciscoconfparse#215]
Adding a logger which uses _"enqueue=True"_ makes a application hang up until SIGINT signal.
Tested workflow consist of _celery_ using pools with _gevent_ and _ciscoconfparse_ as dependency of _napalm_.
Latest version of ciscoconfparse for which the workflow doesn't break is 1.5.36.

The hangup comes from the fact, that celery patches _thread_ library when using gevent - which doesn't [support multiprocess.Queue](https://www.gevent.org/api/gevent.monkey.html#gevent.monkey.patch_thread) (see "Caution" box), which is used by loguru when logger with enqueue parameter set to True is added as handler.
Loguru by default uses ENV variable to control that setting (LOGURU_ENQUEUE=False). Maybe ciscoconfparse could use default value for that setting?

I know that in 1.6.0 an option to disable the logger was added (#211), but still disabling the logger will happen after the "add" command, which already will make thread non-responding.

**Comment by mpenning** [comment]
@TomaszKrassowski could you provide an example of what is broken in your ciscoconfparse use-case?  Please use version 1.6.8 (it will be released on pypi today).

**Comment by TomaszKrassowski** [comment]
@mpenning Using python REPL in a shell with gevent and ciscoconfparse installed via pip:
```
TOKRA:~$ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gevent.monkey import patch_all
>>> patch_all()
True
>>> import ciscoconfparse

```
Freeze occurs during import of the ciscoconfparse - because it automatically adds a logger with enqueue set to True via __init__.py.

**Comment by mpenning** [comment]
I can reproduce this problem in ciscoconfparse version 1.6.8 with:

```python
from gevent.monkey import patch_all

patch_all()
from ciscoconfparse import CiscoConfParse

config = ""
parse = CiscoConfParse(config.splitlines())

# in ciscoconfparse version 1.6.8, Python hangs at CiscoConfParse() above...
```

This is a known issue with `loguru` and `gevent`...
- https://github.com/Delgan/loguru/issues/352
- https://github.com/Delgan/loguru/issues/258

As mentioned in loguru issue #352, the simplest fix is to disable gevent threading...
```python
from gevent.monkey import patch_all

patch_all(thread=False)   # <-  disable gevent threading...
from ciscoconfparse import CiscoConfParse

config = ""
parse = CiscoConfParse(config.splitlines())
```

However, In version 1.6.9, you don't have to disable gevent threading support...
```python
from ciscoconfparse.ccp_util import import_gevent_monkey
from ciscoconfparse import CiscoConfParse

# import gevent and monkey with import_gevent_monkey()
gevent, monkey = import_gevent_monkey()
monkey.patch_all()

config = ""
parse = CiscoConfParse(config.splitlines())
```

`import_gevent_monkey()` instead of normal python imports is a hack for sure, but hopefully that's acceptable.

Please let me know whether this completely fixes your ciscoconfparse and gevent use-case...

**Comment by TomaszKrassowski** [comment]
@mpenning Could you explain how does import_gevent_monkey resolves the issues with gevent? I can't quite follow what the changes added in _c7b355c_ commit do, apart from checking if gevent/gevent.monkey can be imported.
The main thing is, that in my case, I can't control gevent patching, as it is called by celery framework (https://github.com/celery/celery/blob/d32356c0e46eefecd164c55899f532c2fed2df57/celery/__init__.py#L117)
The code sample I have copied in my previous response, was just the simplest case of how the issue can be reproduced.

**Comment by mpenning** [comment]
>I can't control gevent patching, as it is called by celery framework

Is there a bug with celery?  celery is breaking ciscoconfparse,
