### ISSUE TITLE
ciscoconfparse 1.6.24 install from pypi fails

### ISSUE THREAD

**Issue by ktbyers** [mpenning/ciscoconfparse#220]
Was doing a system build that included ciscoconfparse and this failed:

```
$ pip install ciscoconfparse==1.6.24
Collecting ciscoconfparse==1.6.24
  Using cached ciscoconfparse-1.6.24-py3-none-any.whl (118 kB)
Requirement already satisfied: dnspython<3.0.0,>=2.1.0 in ./VENV/py3_venv/lib/python3.7/site-packages (from ciscoconfparse==1.6.24) (2.2.0)
Requirement already satisfied: passlib<2.0.0,>=1.7.4 in ./VENV/py3_venv/lib/python3.7/site-packages (from ciscoconfparse==1.6.24) (1.7.4)
ERROR: Could not find a version that satisfies the requirement ipaddress>=2.1.11 (from ciscoconfparse) (from versions: 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.21, 1.0.22, 1.0.23)
ERROR: No matching distribution found for ipaddress>=2.1.11
```

I assume that was supposed to be `ipaddr` and not `ipaddress`? Is that even needed now that you are requiring Python 3.6 or greater?

https://github.com/mpenning/ciscoconfparse/blob/master/pyproject.toml#L38

**Comment by mpenning** [comment]
Hello @ktbyers ,

Thank you for reporting this problem... please test version 1.6.25, which does not care about requirements for the `ipaddress` module (this was left-over from days of Python 2.7 support).  As you mentioned, `ipaddress` is part of stdlib now.

**Comment by ktbyers** [comment]
Yep, fixed:

```
$ pip list | grep ciscoconfparse
ciscoconfparse        1.6.25
$ pip list | grep napalm
napalm                3.3.1
```

Longer term have you thought about using poetry for dependency install  in gitHub actions (so you have more consistent behavior between GH-actions dependency install and pypi behavior)? In other words, that this issue would have been caught via GH-actions?

I think Nornir is doing this and I have a second example somewhere (using Poetry with GH-actions).
