### ISSUE TITLE
prefixlen not working for setting a value

### ISSUE THREAD

**Issue by mariam-azad** [mpenning/ciscoconfparse#225]
I am trying to change the subnet mask of a a subnet by using prefixlen function but i get the error "AttributeError:Cant set attribute"

![image](https://user-images.githubusercontent.com/63309318/154510422-3295d3c8-4509-4b41-b153-16c50feb81f3.png)

The expected behaviour should be
x=IPv4Obj("10.1.1.1/32")
x.prefixlen=30
x shuld be 10.1.1.1/30

Environment:

- Operating System and OS version: Windows 10
- Python version: 3.8.2
- ciscoconfparse version: 1.5.1

**Comment by dwenjii** [comment]
> ciscoconfparse version: 1.5.1

Hey @mariam-azad.  I think you should see if you have the same problem in the latest version of ciscoconfparse.  It'd be kindof embarrassing to file a bug against something that works in recent code.

Think of it another way.  I doubt @mpenning is going to go back and fix something in 1.5.1.  I think the most recent ciscoconfparse is [version 1.6.34](https://pypi.org/project/ciscoconfparse/)

Pease brother and keep giving to the community!

**Comment by mpenning** [comment]
I verified that this problem does not exist in 1.6.34... We will close out this bug report.
