### ISSUE TITLE
[Bug]: CiscoConfParse.sync_diff returns "uncfg" line for childs and parents

### ISSUE THREAD

**Issue by kornoa** [mpenning/ciscoconfparse#226]
### Contact Details

korte.noack@controlware.de

### What happened?

loaded config:
[
    "interface GigabitEthernet1",
    " description Test1",
    "interface GigabitEthernet2",
    " description Test2"
]

reference_config  = [
    "interface GigabitEthernet1",
    " description Test1-New",
    "interface GigabitEthernet3",
    " description Test3"
]

calling sync_diff

--> output:
interface GigabitEthernet1
 no  description Test1
 no interface GigabitEthernet2
 no  description Test2
interface GigabitEthernet1
 description Test1-New
interface GigabitEthernet3
 description Test3

--> expected:
interface GigabitEthernet1
 no  description Test1
no interface GigabitEthernet2
interface GigabitEthernet1
 description Test1-New
interface GigabitEthernet3
 description Test3

Deleting sub-command (child) "no description Test2" for "interface GigabitEthernet2", which is deleted one line above makes no sense and will lead to errors if deploying to a Cisco IOS device.
If you accept this bug report, I can provide a fix and create a pull request.

### CiscoConfParse Version

1.6.36

### What Operating System are you using?

Microsoft Windows

### What Python version(s) have this problem?

Python 3.9

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
import ciscoconfparse

config1 = [
    "interface GigabitEthernet1",
    " description Test1",
    "interface GigabitEthernet2",
    " description Test2"
]
cfg1 = ciscoconfparse.CiscoConfParse(config=config1)
reference_config  = [
    "interface GigabitEthernet1",
    " description Test1-New",
    "interface GigabitEthernet3",
    " description Test3"
]

diff = cfg1.sync_diff(cfgspec=reference_config, linespec='.*')
print("\n".join(diff))
```

### Python tracebacks

```shell
no tracebacks
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mpenning** [comment]
Thank you for the report... I'll fix these issues.
