### ISSUE TITLE
[Bug]: BaseCfgLine.add_uncfgtext sets wrong indent if object has no parent but children

### ISSUE THREAD

**Issue by kornoa** [mpenning/ciscoconfparse#227]
### Contact Details

korte.noack@controlware.de

### What happened?

loaded config:
````
[
    "interface GigabitEthernet1",
    "interface GigabitEthernet2",
    " description Test1",
    "interface GigabitEthernet3"
]
````

reference config:
````
[
    "interface GigabitEthernet1",
    "interface GigabitEthernet4"
]
````

--> returns:
````
[
" no interface GigabitEthernet2",
" no  description Test1",
" no interface GigabitEthernet3",
"interface GigabitEthernet4"
]
````
--> correct would be:
````
[
"no interface GigabitEthernet2",
" no  description Test1",
" no interface GigabitEthernet3",
"interface GigabitEthernet4"
]
````

Method add_uncfgtext uses `myindent = self.parent.child_indent`. But self.parent is initializied as --> self. Thus top level config line with children returns indent of children.

Suggested fix: Use self.indent instead of myindent in `self.uncfgtext = myindent * " " + "no " + conftext`

### CiscoConfParse Version

1.6.36

### What Operating System are you using?

Microsoft Windows

### What Python version(s) have this problem?

Python 3.9

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
import ciscoconfparse

config1 = [
    "interface GigabitEthernet1",
    "interface GigabitEthernet2",
    " description Test1",
    "interface GigabitEthernet3",
]
cfg1 = ciscoconfparse.CiscoConfParse(config=config1)
reference_config  = [
    "interface GigabitEthernet1",
    "interface GigabitEthernet4",
]

diff = cfg1.sync_diff(cfgspec=reference_config, linespec='.*')
print("\n".join(diff))
```

### Python tracebacks

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mpenning** [comment]
You seem to have made a mistake in this config:
> --> correct would be:
```
[
"no interface GigabitEthernet2",
" no  description Test1",
" no interface GigabitEthernet3",
"interface GigabitEthernet4"
]
```

`interface GigabitEthernet3` is indented, but I think you're saying it should not be.

For the record, indenting the response does not affect Cisco IOS but I'll endeavor to fix in line with your expectations.

**Comment by mpenning** [comment]
I also should highlight this from `CONTRIBUTING.md`...
> Please email Mike Pennington before writing a PR.

There is little point in two people solving this problem at the same time

**Comment by kornoa** [comment]
` no interface GigabitEthernet2` is intended as it has children. But it should not be intended.
Your are right this is just a cosmetical issue.

**Comment by mpenning** [comment]
FYI, I have fixes sitting on my laptop... they need to be simplified a bit before I merge it into master... apologies for the radio silence, but the heavy lifting should be done
