### ISSUE TITLE
[Bug]: Cisco IOS-XR banner newlines lost

### ISSUE THREAD

**Issue by mwri** [mpenning/ciscoconfparse#229]
### What happened?

Using this contrived Cisco IOS-XR config:

```
!! IOS XR Configuration 7.3.2
!! Last configuration change at Fri Mar 11 02:46:55 2022 by wibble
!
hostname router1.domain
banner login &
=========================
Wibble0
Wibble1

Wibble2
Wibble3
=========================
&
logging ipv4 dscp cs2
logging ipv6 dscp cs2
end
```

Parsing this, the newline(s) in the banner is skipped by the parse as though it's not there, thus all line numbers after the newline are incorrect, and reconstructing the config produces a result different to the original.

### CiscoConfParse Version

1.6.40

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.9, Python 3.8

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse

config = """!! IOS XR Configuration 7.3.2
!! Last configuration change at Fri Mar 11 02:46:55 2022 by wibble
!
hostname router1.domain
banner login &
=========================
Wibble0
Wibble1

Wibble2
Wibble3
=========================
&
logging ipv4 dscp cs2
logging ipv6 dscp cs2
end"""

parse       = CiscoConfParse(config.splitlines(), syntax='ios')
banner_2to5 = [c.text for c in parse.find_objects('^banner')[0].children[2:5]]

# fails
assert banner_2to5 == ['Wibble1', '', 'Wibble2'], banner_2to5
# fails
assert '\n'.join([c.text for c in parse.find_objects('')]) == config
```

### Python tracebacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: ['Wibble1', 'Wibble2', 'Wibble3']
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mpenning** [comment]
Hi,

Could you test parsing with `ignore_blank_lines=False`?

```python
parse = CiscoConfParse(config.splitlines(), syntax='ios', ignore_blank_lines=False, debug=0)
```

**Comment by mwri** [comment]
I agree, with `ignore_blank_lines=False` it works entirely as I would expect. Thank you...

**Comment by mwri** [comment]
I guess my feeling on this is that the default should really be `ignore_blank_lines=True` in the next major release, since that is required to not potentially substantively alter a config.

**Comment by mpenning** [comment]
> I guess my feeling on this is that the default should really be ignore_blank_lines=True in the next major release, since that is required to not potentially substantively alter a config.

I don't agree that `ignore_blank_lines=True` should be default behavior, but I changed banner and macros to always allow blank lines.

I just pushed it to git HEAD if you want to try it out...
