### ISSUE TITLE
[Bug]: empty line crash in 1.6.41 but not 1.6.40

### ISSUE THREAD

**Issue by FliesLikeABrick** [mpenning/ciscoconfparse#248]
### Contact Details

Via issue ticket 

### What happened?

Backtrace in __init__, _bootstrap_obj_init_ios, assign_parent_to_closing_braces

On 1.6.40 and older the code has run without failure

### CiscoConfParse Version

1.6.41

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others, Other (please specify): CentOS 7.x and Cygwin

### What Python version(s) have this problem?

Python 3.6.9, 3.6.8.  Probably others/all, we have not found a python version that avoids this issue

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
# note newline in `config`
config = """feature fex

feature lldp""".splitlines()


from ciscoconfparse import CiscoConfParse
parse = CiscoConfParse(config, syntax="ios")
```

### Python tracebacks

```shell
>>> parse = CiscoConfParse(config, syntax="ios")
2022-10-03 11:05:01.132 | ERROR    | ciscoconfparse.ciscoconfparse:_bootstrap_obj_init_ios:5317 - An error has been caught in function '_bootstrap_obj_init_ios', process 'MainProcess' (1473), thread 'MainThread' (25769803792):
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/home/ryarawdo/env/lib/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 506, in __init__
    ccp_ref=self,
            └ <CiscoConfParse: None lines / syntax: ios / comment delimiter: '!' / factory: False / encoding: 'UTF-8'>
  File "/home/ryarawdo/env/lib/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 4445, in __init__
    self._list = self._bootstrap_obj_init_ios(initlist)
    │    │       │    │                       └ ['feature fex\n', '\n', 'feature lldp\n']
    │    │       │    └ <function ConfigList._bootstrap_obj_init_ios at 0x6fffdf307b8>
    │    │       └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 'feature fex
    │    │         '>, <IOSCfgLine # 1 '
    │    │         ' (parent is # 0)>, <IOSCfgL...
    │    └ [<IOSCfgLine # 0 'feature fex
    │      '>, <IOSCfgLine # 1 '
    │      ' (parent is # 0)>, <IOSCfgLine # 2 'feature lldp
    │      '>]
    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 'feature fex
      '>, <IOSCfgLine # 1 '
      ' (parent is # 0)>, <IOSCfgL...
> File "/home/ryarawdo/env/lib/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 5317, in _bootstrap_obj_init_ios
    self._list = assign_parent_to_closing_braces(input_list=self._list)
    │    │       │                                          │    └ [<IOSCfgLine # 0 'feature fex
    │    │       │                                          │      '>, <IOSCfgLine # 1 '
    │    │       │                                          │      ' (parent is # 0)>, <IOSCfgLine # 2 'feature lldp
    │    │       │                                          │      '>]
    │    │       │                                          └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 'feature fex
    │    │       │                                            '>, <IOSCfgLine # 1 '
    │    │       │                                            ' (parent is # 0)>, <IOSCfgL...
    │    │       └ <function assign_parent_to_closing_braces at 0x6fffdf7ee18>
    │    └ [<IOSCfgLine # 0 'feature fex
    │      '>, <IOSCfgLine # 1 '
    │      ' (parent is # 0)>, <IOSCfgLine # 2 'feature lldp
    │      '>]
    └ <ConfigList, syntax='ios', comment='!', conf=[<IOSCfgLine # 0 'feature fex
      '>, <IOSCfgLine # 1 '
      ' (parent is # 0)>, <IOSCfgL...
  File "/home/ryarawdo/env/lib/python3.6/site-packages/ciscoconfparse/ciscoconfparse.py", line 338, in assign_parent_to_closing_braces
    if len(obj.text)>=1 and obj.text.rstrip()[-1] == '{':
           │   │            │   └ <property object at 0x6fffe0dd908>
           │   │            └ <IOSCfgLine # 1 '
           │   │              ' (parent is # 0)>
           │   └ <property object at 0x6fffe0dd908>
           └ <IOSCfgLine # 1 '
             ' (parent is # 0)>

IndexError: string index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by FliesLikeABrick** [comment]
Issue does not occur if the empty line is taken out of the config, or if <= 1.6.40 is used. 

Cisco NX-OS 7.3 and others do generate configurations with blank lines, for example this is the last output of "show run" on a device of ours:
logging logfile messages 6
logging server 10.110.180.23
logging server 10.30.183.174
logging source-interface loopback0
logging timestamp milliseconds
logging monitor 6
logging level local6 6
no logging console

scheduler aaa-authentication username VCC_Network_Cisco password 7 redacted

scheduler job name auto_checkpoint
checkpoint

end-job

scheduler job name VCC_NW_Cisco_auto_checkpoint
checkpoint

end-job

scheduler schedule name 8hr_checkpoint
  job name auto_checkpoint
  time start 2013:03:12:21:14 repeat 0:8:0

scheduler schedule name 8hr_checkpoint_VCC_NW_Cisco
  job name VCC_NW_Cisco_auto_checkpoint
  time start 2017:06:01:17:42 repeat 0:8:0

**Comment by mpenning** [comment]
Hello,

At this time, [python3.6 is End of Life][1] ( also see the [official python devguide][2] ).

Would you consider using python3.7?  I have a copy of python 3.7.0 under debian11 and cannot reproduce the problem under 3.7.0.

  [1]: https://discuss.python.org/t/is-python-3-6-eol/12765
  [2]: https://devguide.python.org/versions/
