### ISSUE TITLE
[Bug]: ciscoconfparse.get_config_lines TypeError: open() argument after ** must be a mapping, not method

### ISSUE THREAD

**Issue by taiwanstanily** [mpenning/ciscoconfparse#249]
### Contact Details

taiwanstanily+gitstanily@gmail.com

### What happened?

2022-10-04 10:31:08.862 | ERROR    | ciscoconfparse.ciscoconfparse:__init__:485 - An error has been caught in function '__init__', process 'MainProcess' (13852), thread 'MainThread' (13468):

### CiscoConfParse Version

1.6.41

### What Operating System are you using?

Microsoft Windows

### What Python version(s) have this problem?

Python 3.6

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse

# Parse the config into objects
parse = CiscoConfParse('./config/bigip.conf',syntax='junos',comment='#')

# Iterate over all the interface objects
for intf_obj in parse.find_objects('^interface'):
    print("ciscoconfparse object: " + intf_obj)
```

### Python tracebacks

```shell
Traceback (most recent call last):

  File ".\f5parsetest.py", line 4, in <module>
    parse = CiscoConfParse('./config/bigip.conf',syntax='junos',comment='#')
            └ <class 'ciscoconfparse.ciscoconfparse.CiscoConfParse'>

> File "C:\Users\stanley\Anaconda3\envs\py-3-6-13\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 485, in __init__
    config = self.get_config_lines(config=config, logger=logger)
             │    │                       │              └ <loguru.logger handlers=[(id=1, level=10, sink=<stdout>)]>
             │    │                       └ './config/bigip.conf'
             │    └ <function CiscoConfParse.get_config_lines at 0x0000015AD7934598>
             └ <CiscoConfParse: None lines / syntax: junos / comment delimiter: '#' / factory: False / encoding: 'cp950'>

  File "C:\Users\stanley\Anaconda3\envs\py-3-6-13\lib\site-packages\ciscoconfparse\ciscoconfparse.py", line 582, in get_config_lines
    with open(config, **self.openargs) as fh:
              │         │    └ <function Logger.catch.<locals>.Catcher.__call__.<locals>.catch_wrapper at 0x0000015AD7934950>
              │         └ <CiscoConfParse: None lines / syntax: junos / comment delimiter: '#' / factory: False / encoding: 'cp950'>
              └ './config/bigip.conf'

TypeError: open() argument after ** must be a mapping, not method
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
Hello,

At this time, [python3.6 is End of Life][1] ( also see the [official python devguide][2] ).

Please upgrade to a supported version of python.

  [1]: https://discuss.python.org/t/is-python-3-6-eol/12765
  [2]: https://devguide.python.org/versions/

**Comment by taiwanstanily** [comment]
Hi mpenning
I try to use python 3.7.4. Same issue.
downgrade ciscoconfparser to 1.6.40 is working fine.

thanks for your reply.
