### ISSUE TITLE
[Bug]: please don't assume python types in your assertions

### ISSUE THREAD

**Issue by daemonkeeper** [mpenning/ciscoconfparse#256]
### What happened?

I've noticed, you started adding type assertions to your library. While the intent is good, please do not hardcode types. Please do not assume or hardcode arguments of your methods and functions to be a particular Python types. Here are some examples:

https://github.com/mpenning/ciscoconfparse/blob/1.7.0/ciscoconfparse/ciscoconfparse.py#L3331

```python
        assert isinstance(cfgspec, (list, tuple, Iterator)), "FATAL - `cfgspec` requires a python Iterable, typically a `list()`."
        assert isinstance(linespec, str) and len(linespec) > 0, "FATAL - `linespec` requires a python string."
        assert isinstance(unconfspec, str) and len(unconfspec) > 0, "FATAL - `unconfspec` requires a python string."
```

https://github.com/mpenning/ciscoconfparse/blob/main/ciscoconfparse/ciscoconfparse.py#L3458

```python
        assert isinstance(before_config, list) or os.path.isfile(before_config)
        assert isinstance(after_config, list) or os.path.isfile(after_config)
        assert isinstance(syntax, str) and syntax in set({"ios", "junos"})
        assert isinstance(allow_duplicates, bool)
        assert isinstance(output_format, str) and output_format in set({"dict", "unified"})
```

I understand your intent, and it is generally a good idea to test for data types, but you should not demand _types_ but _features_. Don't expect people to pass you a ``set``, a ``list`` or a ``dict`` or any other base-type. 

Instead, please require _features_: https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes. You may have seen these used in the standard library already. 

For all practical intents and purposes it's better to test the provided argument for a _feature_ you need, and not for a _type_.  Some people, including me, may not actually pass you a base type as an argument to your library, but an object instance that _behaves_ like the base type you expect. Here's an example:

```python
In [30]: class MyList(collections.abc.Sequence):
    ...:     container_list: list = []
    ...:     def __init__(self, *items):
    ...:         self.container_list.extend(items)
    ...:     def __getitem__(self, item):
    ...:         return self.container_list[item]
    ...:     def __len__(self):
    ...:         return len(self.container_list)
    ...:
    ...: mylist = MyList(1, 2, 3)
    ...:

In [31]: isinstance(mylist, list)
Out[31]: False

In [32]:

In [32]: isinstance(mylist, collections.abc.Sequence)
    ...:
Out[32]: True

In [33]: mylist[0]
Out[33]: 1

In [34]: for item in mylist:
    ...:     print(item)
    ...:
1
2
3
```

Your library would bail out for this instances class, even though it pefectly provides all the features you need / expect. I'd strongly urge you to test for features. In 99.5% of the cases where you test for ``dict``/``list``/ you really mean ``Mapping``/``Sequence``. This also saves you from doing things like:

```python
        assert isinstance(cfgspec, (list, tuple, Iterator)), "FATAL - `cfgspec` requires a python Iterable, typically a `list()`."
````

since list, tuple and actual iterators all implement "[Iterable](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable)". This applies like-wise to numbers: https://docs.python.org/3/library/numbers.html.

I would discourage you from testing for ``str`` for similar reasons, or at least don't actually assert for the type. 

I'd also like to point you to Python PEP-483 type hints: https://docs.python.org/3/library/typing.html. What you're trying to achieve, is perhaps better solved at a language level. I'd suggest you to remove your asserts and replace, e.g.:

```python
    def __init__(
        self,
        before_config=None,
        after_config=None,
        syntax="ios",
        ordered_diff=False,
        allow_duplicates=False,
        output_format="unified",
        debug=0,
    ):
...
        assert isinstance(before_config, list) or os.path.isfile(before_config)
        assert isinstance(after_config, list) or os.path.isfile(after_config)
        assert isinstance(syntax, str) and syntax in set({"ios", "junos"})
        assert isinstance(allow_duplicates, bool)
        assert isinstance(output_format, str) and output_format in set({"dict", "unified"})

```

by

```python
    def __init__(
        self,
        before_config: Sequence | os.PathLike = None,
        after_config: Sequence | os.PathlLke = None,
        syntax: Literal["ios", "junos"] = "ios",
        ordered_diff: bool =False,
        allow_duplicates: bool =False,
        output_format: Literal["unified", "dict"] ="unified",
        debug: bool = 0, # unless you really mean "0" here. 
    ):


        # you may wish to check https://docs.python.org/3/library/pathlib.html for these
        if isinstance(before_config, os.PathlLke):
           assert os.path.isfile(before_config)
        if isinstance(after_config, os.PathlLke):
          assert os.path.isfile(after_config)
```

On a side-node: even though you default before_config to None, you never accept that as a type:

```python
        before_config=None,
...
        assert isinstance(before_config, list) or os.path.isfile(before_config)
```

If you really want to support ``None`` there, you may wish to change this assert, or use a type hint:

```
        before_config: Sequence | os.PathLike  | None = None,
```

### CiscoConfParse Version

1.7, git main

### What Operating System are you using?

Microsoft Windows, MacOS, Linux - Debian, Ubuntu, CentOS, RHEL or others, OpenBSD, FreeBSD, NetBSD

### What Python version(s) have this problem?

Python 3.10

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
N/A
```

### Python tracebacks

```shell
File "/Users/me/Projects/pyenv/lib/python3.10/site-packages/ciscoconfparse/ciscoconfparse.py", line 3332, in sync_diff
    assert isinstance(linespec, str) and len(linespec) > 0, "FATAL - `linespec` requires a python string."
AssertionError: FATAL - `linespec` requires a python string.
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by daemonkeeper** [comment]
On another note, I noticed you added also code like this:

```python
    def build_diff_obj_list(
        self, parse=None, default_diff_word=None, consider_whitespace=False
    ):
...
        assert parse is not None
        assert isinstance(default_diff_word, str)
```
I'd argue you contract yourself here. You literally set ``build_diff_obj_list``'s arguments to None, None by default in the method's signature, just to check in the first that they're not ``None``. Hopefully, you agree with me, that you should better just write

```python
    def build_diff_obj_list(
        self, parse, default_diff_word, consider_whitespace
    ):
```

then. Python already provides you the tools and grammar to ensure that this method's arguments can't be None.

**Comment by mpenning** [comment]
Thank you for submitting this... the issue itself is really long.  I will endeavor to hit the main points, but let me know if I miss something really important....

> Please don't assume types... Some people, including me, may not actually
> pass you a base type as an argument to your library
> ... and ...
> While the intent is good, please do not hardcode types
> it's better to test the provided argument for a feature you need, and not for a type.

Please checkout a new `git` branch and submit a PR with all your suggested changes.

> I'd also like to point you to Python PEP-483

Sadly, PEP-483 does NOT enforce types on external data inputs.  I will add PEP-483 hints to ciscoconfparse in a future release.

> test for mapping or sequence.

Our unit tests assume `dict`, `list`, `tuple`, `str` *external inputs* all over the place.  Those types are instances of `mapping` / `sequence`.  Status-quo is "good enough"; I do not yet see a compelling cost / benefit to change... but as I said above, you're welcome to checkout a new branch and submit a PR.

**Comment by mpenning** [comment]
FYI, changes in version 1.7.8+ implement some simplifications relevant to this issue...
