### ISSUE TITLE
Vulnerability due to transitive dependency

### ISSUE THREAD

**Issue by syn-4ck** [mpenning/ciscoconfparse#257]
A high severity vulnerability is detected by Snyk in `ciscoconfparse` package due to `pyroma@4.1 › wheel@0.30.0`.

![image](https://user-images.githubusercontent.com/43778014/212543894-2ea69137-0ed7-4341-92ba-7d2e912c72a1.png)

Could you review the dependency and bump the version (I think that the latest is still vulnerable) or try to **pin** the wheel package in version `0.38.0`? Thanks in advance.

Regards.

**Comment by mpenning** [comment]
I don't think this CVE matters much for ciscoconfparse, but the latest `git HEAD` commit hash (`79ef365dad5aa3ac047a3b71d7aa68ec1a60221a`) has upgraded package dependencies...
