### ISSUE TITLE
[Bug]: CiscoConfParse versions affecting threading

### ISSUE THREAD

**Issue by superloopnetwork** [mpenning/ciscoconfparse#265]
### Contact Details

wailit@gmail.com

### What happened?

I've been troubleshooting as to why when I upgrade my ciscoconfparse package to the latest, my code breaks when it does threading. This is what I noticed; When I install ciscoconfparse v1.5.46 and below - threading works fine and my code completes. If I update to anything above v1.5.48, threading stalls/hang/lock and never completes. I would have to press Ctrl-C to terminate:
```
  File "/usr/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```
By any chance, do you know if ciscoconfparse some how would affect the threading process?

### CiscoConfParse Version

v1.5.48 +

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.8, Python 3.7

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

Installing v1.5.46 with successful completion of 'show clock':
```python

root@devvm:~/superloop# pip3 install ciscoconfparse==1.5.46  
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
Collecting ciscoconfparse==1.5.46
  Using cached ciscoconfparse-1.5.46-py3-none-any.whl (94 kB)
Requirement already satisfied: loguru in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.46) (0.6.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.46) (0.4.6)
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.46) (2.3.0)
Requirement already satisfied: passlib in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.46) (1.7.4)
Installing collected packages: ciscoconfparse
Successfully installed ciscoconfparse-1.5.46
WARNING: You are using pip version 20.2.2; however, version 23.0 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

root@devvm:~/superloop# python3.7 superloop.py host exec "show clock" --node core.*sw       
Password: 
<_MainThread(MainThread, started 139972616414976)>
<Thread(Thread-1, started 139972460959488)>
core.sw.superloop.ktch: 15:34:36.186 EST Mon Feb 13 2023

[>] Complete [0:00:09.970271]
```

Uninstalling v1.5.46:
```
root@devvm:~/superloop# pip3 uninstall ciscoconfparse==1.5.46                          
Found existing installation: ciscoconfparse 1.5.46
Uninstalling ciscoconfparse-1.5.46:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/ciscoconfparse-1.5.46.dist-info/*
    /usr/local/lib/python3.7/dist-packages/ciscoconfparse/*
Proceed (y/n)? y
  Successfully uninstalled ciscoconfparse-1.5.46
```

Installing v1.5.48 with unsuccessful completion of 'show clock' (need to hit Ctrl-C to exit as it never finishes the thread):
```
root@devvm:~/superloop# pip3 install ciscoconfparse==1.5.48
WARNING: Keyring is skipped due to an exception: entry_points() got an unexpected keyword argument 'group'
Collecting ciscoconfparse==1.5.48
  Using cached ciscoconfparse-1.5.48-py3-none-any.whl (97 kB)
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.48) (2.3.0)
Requirement already satisfied: passlib in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.48) (1.7.4)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.48) (0.4.6)
Requirement already satisfied: loguru in /usr/local/lib/python3.7/dist-packages (from ciscoconfparse==1.5.48) (0.6.0)
Installing collected packages: ciscoconfparse
Successfully installed ciscoconfparse-1.5.48
WARNING: You are using pip version 20.2.2; however, version 23.0 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
root@devvm:~/superloop# python3.7 superloop.py host exec "show clock" --node core.*sw
Password: 
<_MainThread(MainThread, started 140222931838720)>
<Thread(loguru-writer-1, started daemon 140222818985728)>
core.sw.superloop.ktch: 15:36:14.644 EST Mon Feb 13 2023

^CTraceback (most recent call last):
  File "superloop.py", line 116, in <module>
    main()
  File "superloop.py", line 111, in main
    args.func(args)
  File "/root/superloop/exec_cmd.py", line 48, in exec_cmd
    multithread_engine(initialize.ntw_device,redirect,argument_command,authentication)
  File "/root/superloop/multithread.py", line 36, in multithread_engine
    some_thread.join()
  File "/usr/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

### Python tracebacks

```shell
^CTraceback (most recent call last):
  File "superloop.py", line 116, in <module>
    main()
  File "superloop.py", line 111, in main
    args.func(args)
  File "/root/superloop/exec_cmd.py", line 48, in exec_cmd
    multithread_engine(initialize.ntw_device,redirect,argument_command,authentication)
  File "/root/superloop/multithread.py", line 36, in multithread_engine
    some_thread.join()
  File "/usr/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by superloopnetwork** [comment]
Here is another interesting find. If I comment out an import statement related to ciscoconfparse:
```
#from ciscoconfparse import CiscoConfParse
```
.... and I re-run the code:

```
root@devvm:~/superloop# pip3 list | grep ciscoconfparse              
ciscoconfparse                1.5.48
root@devvm:~/superloop# python3.7 superloop.py host exec "show clock" --node core.*sw
Password: 
<_MainThread(MainThread, started 140482555680512)>
<Thread(Thread-1, started 140482405213952)>
core.sw.superloop.ktch: 17:17:57.244 EST Mon Feb 13 2023

[>] Complete [0:00:09.280634]
```
It's ok... If I uncomment ciscoconfparse, it stalls/hangs/locks... Somehow it seems like ciscoconfparse package may have an effect on threading?

**Comment by mpenning** [comment]
Hello @superloopnetwork 

I cloned superloop git HEAD into a fresh python3.9 virtualenv to reproduce the problem (and `pip install -r requirements.txt`), but I'm getting a traceback when I try to run `superloop.py`.   You have a lot of branches... please let me know which one you're working on in case it helps me get past this issue...

Traceback as FYI...
```shell
$ > python superloop.py -h
Traceback (most recent call last):
  File "/home/mpenning/fixme/superloop/superloop.py", line 9, in <module>
    from auditdiff import auditdiff
  File "/home/mpenning/fixme/superloop/auditdiff.py", line 13, in <module>
    from mediator import mediator
  File "/home/mpenning/fixme/superloop/mediator.py", line 4, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/opt/virtual_env/py39_superloop/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/virtual_env/py39_superloop/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/virtual_env/py39_superloop/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/virtual_env/py39_superloop/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/virtual_env/py39_superloop/lib/python3.9/site-packages/markupsafe/__init__.py)
 $ >
```

**Comment by superloopnetwork** [comment]
Hello @mpenning... 

To save you some time from investigating, I think I've narrowed it down to the culprit... It looks like it's the **loguru** package that is causing issues for me. I noticed it's a dependancy for ciscoconfparse... Version 1.5.5 did not require it.. Newer versions include it...

What gave it away was this; On successful runs I see this:
```
<_MainThread(MainThread, started 139972616414976)>
<Thread(**Thread-1**, started 139972460959488)>
core.sw.superloop.ktch: 15:34:36.186 EST Mon Feb 13 2023

[>] Complete [0:00:09.970271]
```
For unsuccessful runs, I see this:
```
<_MainThread(MainThread, started 140509590161152)>
<Thread(**loguru-writer-1**, started daemon 140509481662208)>
```
I'm not sure why a logger would cause issues for threading. Is it because the thread remains 'open' due to the logger being active? So the thread never gets killed or terminated? Any ideas or work around?

**Comment by superloopnetwork** [comment]
I was able to make further advancements... From this module: https://github.com/mpenning/ciscoconfparse/blob/main/ciscoconfparse/ccp_util.py#L189

If I change this attribute to 'False', and run it, it works!
```
root@devvm:~/superloop# pip3 list | grep ciscoconfparse                                        
ciscoconfparse                1.7.15
root@devvm:~/superloop# python3.7 superloop.py host exec "show clock" --node core.*fw               
Password: 
<_MainThread(MainThread, started 140233623299840)>
<Thread(Thread-1, started 140233463572224)>
core-fw-superloop-ktch: 16:53:32.156 EST Mon Feb 13 2023
core-fw-superloop-ktch: 

[>] Complete [0:00:08.944069]
```
+ Notice it says 'Thread-1' again when allow_enqueue=False.

I'm not sure what that attribute does, but it's working for me now... Any ideas or consequences I will face if I set allow_enqueue=False ?

**Comment by mpenning** [comment]
> loguru package that is causing issues for me

That's not surprising :-)  For all the good it brings, `loguru` is kindof a stick-in-the-mud at times...

> I'm not sure why a logger would cause issues for threading

I'll add my $0.02 here...

- Threading and python are [famously at odds with each other due to the GIL][1] problems.  Many people still find success with python `threading`... however, see next bullet
- For the most part, I use `multiprocessing` instead of threading everywhere.  `multiprocessing` is heavier than `threading` (due to replicating the entire python process), but I have built a lot of stuff on top of multiprocessing with vastly positive results.

Feel free to keep using `threading`... I'm just mentioning my experience with `multiprocessing`.

> If I change this parameter (loguru `allow_enqueue`) to False

Well `allow_enqueue` is not a valid `loguru` parameter.  I have no idea where I got that, but it managed to escape notice until now.  I changed from `allow_enqueue` to `enqueue` in git HEAD... and I pushed that commit to the `main` branch.  Version 1.7.16 will have it in a released version on pypi... I haven't released 1.7.16 yet but I'm close.

[1]: https://stackoverflow.com/a/1294402/667301

**Comment by superloopnetwork** [comment]
Thanks for the above explanation. If I leave `allow_enqueue=False`, what are the consequences? Are there any? Or will ciscoconfparse continue to function as normal?

**Comment by mpenning** [comment]
> Or will ciscoconfparse continue to function as normal?

I think you're asking if you can still use ccp version 1.5.x (which still has `allow_enqueue`).  I'm the guy who says *always* run the latest ciscoconfparse version... keep using 1.5.x if you like, but most people would want the numerous bug fixes and improvements between there and the latest ciscoconfparse.

**Comment by superloopnetwork** [comment]
Hey @mpenning .. I think there was a miscommunication. I was able to install and run the latest and greatest version of ciscoconfparse (v1.7.15) and got it to work by setting the `allow_enqueue` to `False`. I was just curious if it had any impact by me setting it to False. I guess it's more internal to ciscoconfparse.

Thanks for your help!
