### ISSUE TITLE
[Bug]: The banner value was not parsed correctly in the Arista config file

### ISSUE THREAD

**Issue by bethleekor** [mpenning/ciscoconfparse#268]
### Contact Details

bethleekor@gmail.com

### What happened?

The banner is not parsed properly.
The children values are not retrieved when parsing the banner value with find_objects / find_all_children

Using this contrived Arista config (EOS-4.20):
```
!
banner motd
------------------------------------------------------------------------------------------------------------

Warning: This system is restricted to Jin's company.

Authorized users for business purposes only. 
All sessions are monitored and recorded.

------------------------------------------------------------------------------------------------------------
EOF
!
```

(output information)
`banner motd`

### CiscoConfParse Version

1.7.18

### What Operating System are you using?

Microsoft Windows

### What Python version(s) have this problem?

Python 3.10

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse

def main():    
  config_str = """
!
ntp server 172.00.00.00 prefer
ntp server 00.00.00.00
!
banner motd
------------------------------------------------------------------------------------------------------------

Warning: This system is restricted to Jin's company.

Authorized users for business purposes only. 
All sessions are monitored and recorded.

------------------------------------------------------------------------------------------------------------
EOF
!
  """
  

  config = CiscoConfParse(config_str.splitlines(), syntax='ios', ignore_blank_lines=False)
  banner = config.find_objects(r'^banner')
  for value in banner:
    print(value.text)

if __name__ == '__main__':
    main()
```

### Python tracebacks

```shell
banner motd
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
>The banner is not parsed properly.
> The children values are not retrieved when parsing the banner value with find_objects / find_all_children

You have no IOS-syntax children anywhere in your script.  There are no children to be found.

**Comment by bethleekor** [comment]
Thank you for the reply.
I attached Arista config file in the config_str value (There is no separator after "banner motd"). In this case, I would like to know how I can parse the banner information using your library. Could you please provide guidance on this matter?

**Comment by mpenning** [comment]
Technically if all you're doing is parsing an Arista banner, you don't need `CiscoConfParse()`, but if you're already using it, this should work...

```python
from ciscoconfparse import CiscoConfParse

config = """!
!
ntp server 172.00.00.00 prefer
ntp server 00.00.00.00
!
banner motd
------------------------------------------------------------------------------------------------------------

Warning: This system is restricted to Jin's company.

Authorized users for business purposes only.
All sessions are monitored and recorded.

------------------------------------------------------------------------------------------------------------
EOF
!
    """

parse = CiscoConfParse(config.splitlines())
banner_objs = []
in_banner = False
for obj in parse.objs:
    if obj.text == "banner motd":
        in_banner = True
    if in_banner: banner_objs.append(obj)
    if obj.text == "EOF":
        break
```

This was written for readability... you can probably optimize it a bit if you're interested in that.
