### ISSUE TITLE
[Bug]: CiscoConfParse cannot import dnspython during Github Automated test runs.

### ISSUE THREAD

**Issue by mpenning** [mpenning/ciscoconfparse#274]
### Contact Details

mike@pennington.net

### What happened?

- This [github automation test run](https://github.com/mpenning/ciscoconfparse/actions/runs/4958114431/jobs/8870601927) captures the nature of the problem
- For several releases now, automated github 'make test' runs fail, but they pass on my laptop.
  - The problem is related to importing `dnspython`.
  - It's unclear why this passes under all python versions except 3.10
- This issue documents the problem.  I have tried some workarounds, but so far nothing fixes the py3.10 github automation problem

### CiscoConfParse Version

1.7.x

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.10

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
See [this github automation test job](https://github.com/mpenning/ciscoconfparse/actions/runs/4958114431/jobs/8870601927)
```

### Python tracebacks

```shell
ImportError while loading conftest '/home/runner/work/ciscoconfparse/ciscoconfparse/tests/conftest.py'.
conftest.py:29: in <module>
    from ciscoconfparse.ciscoconfparse import CiscoConfParse
../ciscoconfparse/__init__.py:29: in <module>
    from ciscoconfparse.ccp_util import PythonOptimizeCheck
../ciscoconfparse/ccp_util.py:39: in <module>
    from dns.exception import DNSException
E   ModuleNotFoundError: No module named 'dns'
make: *** [Makefile:171: test] Error 4
Error: Process completed with exit code 2.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by bewing** [comment]
Looks like poetry doesn't have requirements in the pyproject.toml file?  Might need to import the existing requirements.txt into poetry:

https://stackoverflow.com/questions/62764148/how-to-import-requirements-txt-from-an-existing-project-using-poetry

**Comment by mpenning** [comment]
We consider this bug triaged now because we stopped testing with Github automation at this point.
