### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'deprecat'

### ISSUE THREAD

**Issue by jpmateo022** [mpenning/ciscoconfparse#275]
### Contact Details

jpmateo022@gmail.com

### What happened?

Hi I received this error when I pulled the latest version of the library

ModuleNotFoundError: No module named 'deprecat'

My workaround was to rever to 1.7.18

### CiscoConfParse Version

1.7.23

### What Operating System are you using?

Linux - Debian, Ubuntu, CentOS, RHEL or others

### What Python version(s) have this problem?

Python 3.9

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
I just pulled the latest version of the library which by this time is 1.7.23
```

### Python tracebacks

```shell
from ciscoconfparse import CiscoConfParse
File "/usr/local/lib/python3.9/site-packages/ciscoconfparse/__init__.py", line 29, in <module>
from ciscoconfparse.ccp_util import PythonOptimizeCheck
File "/usr/local/lib/python3.9/site-packages/ciscoconfparse/ccp_util.py", line 43, in <module>
from deprecat import deprecat
ModuleNotFoundError: No module named 'deprecat'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by mpenning** [comment]
Thank you for the bug report!
