### ISSUE TITLE
[Feature]: IOS-XR Route-policy processed incorrectly

### ISSUE THREAD

**Issue by naveci** [mpenning/ciscoconfparse#279]
### What happened?

Hi all,

I noticed a problem with a script that I wrote where I'm trying to generate a config difference per device that I can then use to update each device. I wrote a Jinja2 template with all the changes required on IOS-XR (route-policy, some BGP neighbors and hsrp settings).

One of the problems that I found is in the route-policy. Below is a snippet from the intended config:
```
route-policy SCB_PATH_CONTROL_IN_RPL
 apply BGP_VPN_IN_PATH_PRIO
 apply BGP_VPN_IN_PATH_REGION
 apply BGP_VPN_IN_INET_LC
end-policy
!
route-policy BGP_VPN_IN_INET_LC
 if destination in (0.0.0.0/0, ::/0) and community matches-any (60500:8000) then
  set local-preference 20000
 endif
end-policy
!
```

When using the following piece of code where listed_conf is coming from my J2 template:
```
        listed_conf = rendered_conf[device].splitlines()
        diffed_conf = parse_dev.req_cfgspec_all_diff(listed_conf)
        changes = "\n".join(diffed_conf)

        print(changes)
```

I get the following from CiscoConfParse:
```
route-policy SCB_PATH_CONTROL_IN_RPL
 apply BGP_VPN_IN_PATH_PRIO
 apply BGP_VPN_IN_INET_LC
!
route-policy BGP_VPN_IN_INET_LC
 if destination in (0.0.0.0/0, ::/0) and community matches-any (60500:8000) then
  set local-preference 20000
!
```

To show that the problem is not coming from J2, here's a snippet of the `listed_conf` list:
```
['route-policy SCB_PATH_CONTROL_IN_RPL', ' apply BGP_VPN_IN_PATH_PRIO', ' apply BGP_VPN_IN_PATH_REGION', ' apply BGP_VPN_IN_INET_LC', 'end-policy', '!', 'route-policy BGP_VPN_IN_INET_LC', ' if destination in (0.0.0.0/0, ::/0) and community matches-any (60500:8000) then', '  set local-preference 20000', ' endif', 'end-policy', '!', 'router bgp 65501', ' neighbor-group BGP_NG_VRF6_ALL', ...]
```

So there are a couple of issues here:
1. The `end-if` and `end-policy` statements are being dropped
2. Some statements within a policy are not copied, because they already exist elsewhere in the config, but under a different policy, ex. `apply BGP_VPN_IN_PATH_REGION`. I think that this means that the parent - child relationship is not respected here.

Please let me know if I can assist fixing this issue.

Kr

### CiscoConfParse Version

1.7.24

### What Operating System are you using?

MacOS

### What Python version(s) have this problem?

Python 3.9

### Show us how to reproduce the problem.  Please tell us if the problem is specific to certain inputs or situations.

```python
from ciscoconfparse import CiscoConfParse

with open("templates/testconf.conf") as dev_conf:
    full_conf = dev_conf.readlines()
parse_dev = CiscoConfParse(full_conf, "ios")

rendered_conf = 'route-policy SCB_PATH_CONTROL_IN_RPL\n apply BGP_VPN_IN_PATH_PRIO\n apply BGP_VPN_IN_PATH_REGION\n apply BGP_VPN_IN_INET_LC\nend-policy\n!\nroute-policy BGP_VPN_IN_INET_LC\n if destination in (0.0.0.0/0, ::/0) and community matches-any (60500:8000) then\n  set local-preference 20000\n endif\nend-policy\n!\n'

listed_conf = rendered_conf.splitlines()
diffed_conf = parse_dev.req_cfgspec_all_diff(listed_conf)
print("\n".join(diffed_conf))
```

### Python tracebacks

```shell
no traceback
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mpenning/ciscoconfparse/blob/main/CONTRIBUTING.md)

**Comment by naveci** [comment]
Although not related to route-policy processing, I see a similar issue with the 'router BGP {ASN}' where this is not in the final diffed output. CiscoConfParse seems to drop the `router bgp 65501`. The section with router hsrp is correct and the parents of the sections are in the final output provided by CiscoConfParse.

It seems to come down to the fact the parent section isn't always respected. I couldn't find whether this is a known problem.

**Comment by mpenning** [comment]
Thank you for filing this issue.  I added a note in README...

> At this point, I discovered that IOS-XR does NOT use the same child indentation nesting that IOS and NX-OS do; see [Github Issue 279](https://github.com/mpenning/ciscoconfparse/issues/279) as an example.  Until further notice, use ciscoconfparse on IOS-XR configurations at your own risk.
