### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by aoforb** [mpenning/ciscoconfparse#298]
Hi,

Did you know your website is down? I am unable to access the docs.
[https://www.pennington.net/py/ciscoconfparse/]()

Thanks

**Comment by mpenning** [comment]
The doc site seems to be accessible from my location.  Please check with your internet provider to troubleshoot the issue.

**Comment by aoforb** [comment]
![image](https://github.com/mpenning/ciscoconfparse/assets/146780854/4e56c218-648c-46ab-a7bc-cfe9dd519538)

Thats from our corporate internet over https, it works on http.

Also using my home internet https just doesn't load but http does.

I see you have gone around changed to http (or something) which has solved it. Previously any links I found were redirected to https .

Anyway all sorted thanks
