### ISSUE TITLE
Please improve Cisco IOS static route parsing (with factory=True)

### ISSUE THREAD

**Issue by bewing** [mpenning/ciscoconfparse#30]
Not sure if you are still improving the different line types, but if you are:

Below is a regexp that will match all the pieces of a static route in IOS, based on the command reference options:

```
^ip\s+route(?:\s+(?:vrf\s+(\S+)))?\s+(\d+\.\d+\.\d+\.\d+)\s+(\d+\.\d+\.\d+\.\d+)\s+(?:(\w\S+)(?:\s+(\d+\.\d+\.\d+\.\d+))?|(\d+\.\d+\.\d+\.\d+))(?:\s+(dhcp))?(?:\s+(global))?(?:\s+(\d+))?(?:\s+(multicast))?(?:\s+name\s+(\S+))?(?:\s+(?:(permanent)|(?:track\s+(\d+))))?(?:\s+tag(\d+))?
```
The match groups (if there is no match, returns None):
0: The whole line
1: Name of the VRF
2. Destination network
3. Destination netmask
4/5:  Destination interface and optional nexthop
6: Destination nexthop if no destination interface
7: dhcp
8: global
9: Administrative distance
10: multicast
11: Route name
12: permanent
13. Tracking item
14: tag #

```python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> p = re.compile(r'^ip\s+route(?:\s+(?:vrf\s+(\S+)))?\s+(\d+\.\d+\.\d+\.\d+)\s+(\d+\.\d+\.\d+\.\d+)\s+(?:(\w\S+)(?:\s+(\d+\.\d+\.\d+\.\d+))?|(\d+\.\d+\.\d+\.\d+))(?:\s+(dhcp))?(?:\s+(global))?(?:\s+(\d+))?(?:\s+(multicast))?(?:\s+name\s+(\S+))?(?:\s+(?:(permanent)|(?:track\s+(\d+))))?(?:\s+tag\s+(\d+))?')
>>> m = p.match("ip route vrf TESTING 1.1.1.1 255.255.255.255 TenGigabitEthernet1/1 4.4.4.4 dhcp global 120 multicast name testing track 12 tag 1")
>>> m.groups()
('TESTING', '1.1.1.1', '255.255.255.255', 'TenGigabitEthernet1/1', '4.4.4.4', None, 'dhcp', 'global', '120', 'multicast', 'testing', None, '12', '1')
>>> m = p.match("ip route 1.1.1.1 255.255.255.255 4.4.4.4 global 150 permanent tag 12")
>>> m.groups()
(None, '1.1.1.1', '255.255.255.255', '4.4.4.4', None, None, None, 'global', '150', None, None, 'permanent', None, '12')
>>>
```

**Comment by mpenning** [comment]
Thank you for the suggestion; I pushed a modified version of this to CiscoConfParse version 1.2.16.

Honestly I'm not done with "factory=True" methods and it's a big change that I'm still thinking through.  There are a massive number of potential improvements I could make to parse various IOS features, and it would slow ciscoconfparse unacceptably if I continue down my existing approach.

All that to say that I *could* significantly change this API, please use with caution while it's still a beta feature.

**Comment by mpenning** [comment]
Duplicate of Github issue #35
