### ISSUE TITLE
Banners not being removed completed

### ISSUE THREAD

**Issue by fabiano-lima** [mpenning/ciscoconfparse#36]
I am using CiscoConfParse for parse a full config to a basic file (removing management lines). Sruggling for removing the banners. Lines are not being completed removed. I´m attaching the files and results for a better view. Wondering if that is a bug or if I am using that incorrect.

![config_full_to_basic](https://cloud.githubusercontent.com/assets/10503095/7210850/add67910-e52b-11e4-911f-8d4968c2c95a.png)
![config_parsed](https://cloud.githubusercontent.com/assets/10503095/7210851/add7deea-e52b-11e4-8ef0-69485c23022d.png)
![config_to_be_parsed_](https://cloud.githubusercontent.com/assets/10503095/7210852/adda72ae-e52b-11e4-9385-c33ac051d8ec.png)

as it accepts only picts for attachments, have uploaded the code and txt files into:
https://github.com/fabiano-lima/ciscoconfparse_banner

Thank you !

**Comment by mpenning** [comment]
This should be fixed in 1.2.19... please test and let me know

**Comment by fabiano-lima** [comment]
Tested, that´s Perfect ! Thank you very much !
