### ISSUE TITLE
JunOS Config Comment Lines

### ISSUE THREAD

**Issue by MrRJ45** [mpenning/ciscoconfparse#39]
After some testing it appears that the regex and line_level function break when you have a line in a JunOS config file. The first line of a config file will always start with, for example:

 ## Last commit: 2015-05-18 15:07:43 BST by jbloggs

I have fixed the regex and added a check for the comment character - this appears to work fine:

I'll submit the changes in a minute if you are happy with them

**Comment by mpenning** [comment]
Thank you for opening a bug on this.  I have been planning some changes to how comments are parsed; unfortunately, the PR you submitted is going another direction.  Work is quite busy these days, but I will endeavor to fix this issue as soon as I can.
