### ISSUE TITLE
Unable to install ciscoconfparse 1.2.23 into Python 3.4.3 Windows

### ISSUE THREAD

**Issue by micyew** [mpenning/ciscoconfparse#41]
Hi,

Not sure did anyone have this issue...I was not able to install 1.2.23 onto my Windows Python 3.4.3...It give any error 'ImportError: No module named 'version_info.version'....

Can I know what is causes it?

C:\>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

C:\>pip install --upgrade ciscoconfparse
Collecting ciscoconfparse
  Using cached ciscoconfparse-1.2.23.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "D:\temp\pip-build-k6qnoy2c\ciscoconfparse\setup.py", line 14, in <module>
        from version_info.version import __version__ as __ccpversion__
      File "D:\temp\pip-build-k6qnoy2c\ciscoconfparse\version_info\__init__.py", line 1, in <module>
        from .version import *
    ImportError: No module named 'version_info.version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in D:\temp\pip-build-k6qnoy2c\ciscoconfparse

**Comment by mpenning** [comment]
This should be fixed in 1.2.24.

Please let me know if it wasn't fixed.

**Comment by micyew** [comment]
Hi,

I tried install from pip or via tar ball but still get the same error...

D:\Z_Python>pip install --upgrade ciscoconfparse
Collecting ciscoconfparse
  Downloading ciscoconfparse-1.2.24.tar.gz (241kB)
    100% |################################| 245kB 465kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "D:\temp\pip-build-ptzas_6p\ciscoconfparse\setup.py", line 14,
in <module>
        from version_info.version import __version__ as __ccpversion__
      File
"D:\temp\pip-build-ptzas_6p\ciscoconfparse\version_info\__init__.py", line
1, in <module>
        from .version import *
    ImportError: No module named 'version_info.version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
D:\temp\pip-build-ptzas_6p\ciscoconfparse


### Tar ball install #####
D:\ciscoconfparse-1.2.24.tar\ciscoconfparse-1.2.24>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from version_info.version import __version__ as __ccpversion__
  File
"D:\Z_Download\ciscoconfparse-1.2.24.tar\ciscoconfparse-1.2.24\version_info\__init__.py",
line 1, in <module>
    from .version import *

**Comment by mpenning** [comment]
``pip3 install --upgrade ciscoconfparse`` worked for me (Windows Vista, Python 3.4.3)

Failing that, try ``pip3 install --upgrade pip`` before installing ciscoconfparse.

**Comment by micyew** [comment]
Did that also fail.....My pip3 is the latest version already.....One thing
is that I go thru' a proxy but I don't think this is the problem....I can
down the ciscoconfparse tar ball but it always have this "No module named
version_info.version" error message...

What is this message?

D:\Z_Python>pip3 --version
pip 7.0.3 from C:\Python34\lib\site-packages (python 3.4)

D:\Z_Python>pip3 install --proxy https://1.1.1.1:8080 --upgrade
ciscoconfparse
Collecting ciscoconfparse
  Downloading ciscoconfparse-1.2.25.tar.gz (242kB)
    100% |################################| 245kB 460kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "D:\temp\pip-build-ak3ujmsw\ciscoconfparse\setup.py", line 14,
in <module>
        from version_info.version import __version__ as __ccpversion__
      File
"D:\temp\pip-build-ak3ujmsw\ciscoconfparse\version_info\__init__.py", line
1, in <module>
        from .version import *
    ImportError: No module named 'version_info.version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
D:\temp\pip-build-ak3ujmsw\ciscoconfparse
