### ISSUE TITLE
ImportError: No module named 'version_info.version' Installing into Pycharm

### ISSUE THREAD

**Issue by bssybeep** [mpenning/ciscoconfparse#45]
I'm receiving an error attempting to install ciscoconfparse 1.2.37 into Pycharm.  Details:
Pycharm Porject Interpreter 3.4.3
pycharm-->project-->settings-->my project-->project interpreter-->green + to install-->select ciscoconfparse-->click install package to dir c:\users\username\AppData\Roaming\Python-->receive ImportError: No module named 'version_info.version' error

this is on WIN7 64-bit SP1

thanks

**Comment by tunkaflux** [comment]
I'm having the same issue. Win7 64-bit SP1, Python 3.4.4. Any solution?

**Comment by mpenning** [comment]
Sadly there is no special installation supported for PyCharm... just use pip to install and then fire up pycharm.

**Comment by tunkaflux** [comment]
Can this be reopened, it's not only pycharm, I have the same error via CLI.

**Comment by tunkaflux** [comment]
Hey Mike,

On 2016-05-01 13:31, Mike Pennington wrote:
> Sadly there is no special installation supported for PyCharm... just
> use pip to install and then fire up pycharm.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub [1]
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/mpenning/ciscoconfparse/issues/45#issuecomment-216070053

I have this issue also without using pycharm... Just python opened via 
CLI, import ciscoconfparse, same error.

**Comment by mpenning** [comment]
@tunkaflux I need more information about how exactly you installed via the CLI before I can reopen this bug.

I downloaded Python3.4.4 for Windows 7 x64, installed with `pip3` and can successfully import CiscoConfParse via Windows 7 CLI.

I know for a fact that if you hg or git clone ciscoconfparse and try to install under Windows it will fail; however, the package from PYPI works just fine.

**Comment by jkldgoefgkljefogeg** [comment]
I am getting this on Windows 10 x64 with Python 3.5.1

python -m pip install ciscoconfparse

> Collecting ciscoconfparse
>   Using cached ciscoconfparse-1.2.40.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\username\AppData\Local\Temp\pip-build-0slsd8c9\ciscoconfparse\setup.py", line 14, in <module>
>         from version_info.version import __version__ as __ccpversion__
>       File "C:\Users\username\appdata\local\temp\pip-build-0slsd8c9\ciscoconfparse\version_info\__init__.py", line 1, in <module>
>         from .version import *
>     ImportError: No module named 'version_info.version'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-build-0slsd8c9\ciscoconfparse\

**Comment by XenonR** [comment]
@jkldgoefgkljefogeg Please Take a look at my Solution provided in issue #59

Regards
