### ISSUE TITLE
Cannot use variable inside linespec

### ISSUE THREAD

**Issue by gfainky** [mpenning/ciscoconfparse#55]
Hello,

I have tried to use this interesting libraries in conjunction with a string-variable inside the  "linespec" argument, but it doesn't work.

For example:
1)
if_temp = '9/2'
linea = parse.find_children(r'.*if_temp$') is NOT working, i.e. returns nothing inside variable linea
2)
linea = parse.find_children(r'.*9/2$') is  working, it returns what i requested.

That's quite a pity because I was trying to automate a long configuration migration task, but without this cannot move forward. I read all documentation but couldn't find anything like that.

Any workaround I could use or is it possible to add it to the enhancement requests?

Thank you.
Giulio.

**Comment by mpenning** [comment]
The proper way to get variable interpolation for a variable named `if_temp` is...

      linea = parse.find_children(r'.{0}$'.format(if_temp))
