### ISSUE TITLE
Feature Request: Return boolean on successful save

### ISSUE THREAD

**Issue by kamakazikamikaze** [mpenning/ciscoconfparse#57]
While it may be a trivial thing and possible to check locally, it would be helpful if the `CiscoConfParse.save_as` method were to confirm that the file save was successful and return a boolean.

``` Python
    def save_as(self, filepath):
        """Save a text copy of the configuration at ``filepath``; this
        method uses the OperatingSystem's native line separators (such as
        ``\\r\\n`` in Windows).

        Returns a boolean if writing to file was successful or not"""
        try:
            with open(filepath, 'w') as newconf:
                for line in self.ioscfg:
                    newconf.write(line+'\n')
            return True
        except IOError:
            return False
```

Perhaps returning the exception could be an option for debugging, so if disk space were full or insufficient permissions occurred, the user could troubleshoot and correct the issue?

**Comment by mpenning** [comment]
I decided against implementing a False return value... instead CiscoConfParse raises the appropriate error... True is returned during a successful save.  Use 1.2.41 (or later) for this behavior

**Comment by kamakazikamikaze** [comment]
Sorry for not responding sooner, but thank you for adding this in. It's great to see that this package is still being developed 😄
