### ISSUE TITLE
Python wheel packages

### ISSUE THREAD

**Issue by ttufts** [mpenning/ciscoconfparse#61]
Is it possible for you to compile down some python wheel packages for pypi?

**Comment by XenonR** [comment]
What do you mean exactly?
Please take a look at https://pypi.python.org/pypi/ciscoconfparse

Regards.

**Comment by ttufts** [comment]
Many pypi modules seem to have moved to pre-compiled 'wheel' files.

https://pypi.python.org/pypi/paramiko/2.0.2
https://pypi.python.org/pypi/cryptography/1.4

I've never tried to do it, but it is very convenient installing on a system
that doesn't have directly access to pypi. I have a work system with strict
proxy blocks and I can't install over the network, I have to download each
module and move it up to that system via USB. Having just the whl files
makes it MUCH easier.

The prevalence of them in pypi makes me think it's not just me.

**Comment by XenonR** [comment]
Never did it myself, i'll take a look into it.
But can't make any promises.

**Comment by XenonR** [comment]
Please give the attached wheel a try.
Regards.
[ciscoconfparse-1.2.40-py2-none-any.zip](https://github.com/mpenning/ciscoconfparse/files/609158/ciscoconfparse-1.2.40-py2-none-any.zip)

**Comment by mpenning** [comment]
Fixed in 1.2.41
