### ISSUE TITLE
interface object properties missing

### ISSUE THREAD

**Issue by bandrel** [mpenning/ciscoconfparse#62]
Add properties for common trunk attributes in properties.

switchport trunk native vlan
switchport trunk allowed vlans

**Comment by XenonR** [comment]
Sounds fairly commanding, no thanks, no please, no money ;)

Take a look at [richardstrnad/ciscoconfparse](https://github.com/richardstrnad/ciscoconfparse)
It already includes trunk_allowed_vlan

> def trunk_allowed_vlan(self):
> """ Returns a list with all Vlans.
> If there is no configuration to allow specific Vlans return an empty list.
> 
> However, if there is 'switchport trunk allowed vlan none' return None (NoneType)
> to be able to differntiate between no configuration and explicit 'none'.
> """

Feel free to extend ciscoconfparse with a property for the native vlan

Regards.

**Comment by mpenning** [comment]
As of CiscoConfParse 1.2.42, this should work now... please let me know if you find gaps...

Usage example follows...

```
from ciscoconfparse import CiscoConfParse

lines = ['!',
    'interface GigabitEthernet 1/1',
    ' switchport mode trunk',
    ' switchport trunk allowed vlan none',
    ' switchport trunk allowed vlan add 2-4094',
    ' switchport trunk native vlan 911',
    '!',
]
cfg = CiscoConfParse(lines, factory=True)
intf_obj = cfg.find_objects('^interface')[0]

print "ALLOWED_VLANS", intf_obj.trunk_vlans_allowed.as_list
print "NATIVE", intf_obj.native_vlan
```
