### ISSUE TITLE
Doing a logical AND in find_objects_w_child()?

### ISSUE THREAD

**Issue by micyew** [mpenning/ciscoconfparse#63]
Is there a way to implement a logical AND in find_objects_w_child()?

Eg. I like to pull out the interface when both of the child config "switchport mode trunk" AND "udld port" present. I know we can do OR using "|" but when I try "&" or "&&" it doesn't work..

How do I accomplish this? Thanks...

**Comment by XenonR** [comment]
Unfortunately not, but you can do it in two steps:

`
all_interfaces = parse.find_objects_w_child(parentspec=r"^interface", childspec=r"switchport mode trunk")
match_interfaces = list()

for obj in all_interfaces:
    if obj.re_search_children(r"udld port"):
        match_interfaces.append(obj)

print(match_interfaces)
`

Regards

**Comment by micyew** [comment]
This is a good one...thanks for the tip....

**Comment by mpenning** [comment]
As of version 1.2.43, you can use `find_objects_w_all_children()`... this is an example...

```
>>> config = ['!',
...           'interface FastEthernet0/1',
...           ' switchport access vlan 532',
...           ' spanning-tree vlan 532 cost 3',
...           '!',
...           'interface FastEthernet0/2',
...           ' switchport access vlan 300',
...           ' spanning-tree portfast',
...           '!',
...           'interface FastEthernet0/3',
...           ' duplex full',
...           ' speed 100',
...           ' switchport access vlan 300',
...           ' spanning-tree portfast',
...           '!',
...     ]
>>> p = CiscoConfParse(config)
>>> p.find_objects_w_all_children('^interface',
...     ['switchport access vlan 300', 'spanning-tree portfast'])
...
[<IOSCfgLine # 5 'interface FastEthernet0/2'>, <IOSCfgLine # 9 'interface FastEthernet0/3'>]
>>>
```
