### ISSUE TITLE
"[FATAL] CiscoConfParse could not open ...."

### ISSUE THREAD

**Issue by tyler-8** [mpenning/ciscoconfparse#68]
I'm grabbing the running-config from a Cisco router using netmiko and then passing that config to ciscoconfparse, but every time I get the error in the subject line. I've tried stripping about the 'Building configuration..." line but I continue to get the error. The "...." is always the first line in the config. Any ideas? I've tried Googling the error and reading through the documentation but all I get are hits on the error in the code itself.

**Comment by mpenning** [comment]
Normally that error comes from an IOError (like file not found).

This is a simple example of what happens when I try to open the directory itself instead of a real file...

```
>>> parse = CiscoConfParse('/home/mpenning/')
[FATAL] CiscoConfParse could not open '/home/mpenning/'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/d.pennington/RHEL6/lib/python2.7/site-packages/ciscoconfparse/ciscoconfparse.py", line 224, in __init__
    raise RuntimeError
RuntimeError
>>>
```

Bottom line, this sounds like a localized problem thus far... Please paste in the complete error message (and perhaps even the config) if you still think this isn't going in the right direction.

**Comment by mpenning** [comment]
Please reopen if you would like to change the status

**Comment by noziwatele** [comment]
I was having trouble with this error too. The example code in this post helped:

[https://github.com/ktbyers/netmiko/issues/580](https://github.com/ktbyers/netmiko/issues/580)

This was failing:

```
run_config = net_connect.send_command("show run")
cisco_cfg = CiscoConfParse(run_config)
```

The key was to '_splitlines_' the config from netmiko, like this:

```
run_config = net_connect.send_command("show run")
cisco_cfg = CiscoConfParse(run_config.splitlines())
```
