### ISSUE TITLE
Factory=True, syntax='ios' doesn't parse NXOS-style static routes

### ISSUE THREAD

**Issue by mpenning** [mpenning/ciscoconfparse#71]
```python

CONFIG = """ip route 0.0.0.0/0 port-channel1 1.1.1.1
ip route 1.1.1.2/32 Vlan42  2.2.2.2"""

parse =CiscoConfParse(CONFIG.splitlines(), syntax='ios', factory=True)
```

Fails with ```ValueError: Could not parse 'ip route 0.0.0.0/0 port-channel1 1.1.1.1'```

This is a known-failure; this configuration will parse correctly when I add a ```factory=True, syntax='nxos'``` parser.  The workaround is to parse with ```factory=False``` (i.e.  the default CiscoConfParse() behavior).

**Comment by voltivo** [comment]
It would be awesome if that could be addressed. Thank you for an amazing toolkit!

**Comment by tide-cheng** [comment]
I have doubts about the result when you add `factory=True, syntax='nxos'` parser. I have tried to test the code above but the error `ValueError: Could not parse 'ip route 0.0.0.0/0 port-channel1 1.1.1.1'` still appeared. It seems regex `_RE_IP_ROUTE` in `models_nxos.py` can't parse 'prefix/mask_length' style static routes. The regex `_RE_IP_ROUTE` matches 'prefix mask' style static routes, is that right?

**Comment by mpenning** [comment]
To use the new nxos parser (alpha-quality at best),

```
from ciscoconfparse import CiscoConfParse

CONFIG = """ip route 0.0.0.0/0 port-channel1 1.1.1.1
ip route 1.1.1.2/32 Vlan42  2.2.2.2"""

parse =CiscoConfParse(CONFIG.splitlines(), syntax='nxos', factory=True)
```

**Comment by voltivo** [comment]
Thank you!
