### ISSUE TITLE
models_cisco: `manual_speed' and 'manual_duplex' properties missing from model

### ISSUE THREAD

**Issue by bandrel** [mpenning/ciscoconfparse#74]
The manual_speed and manual_duplex properties are missing from the model.  I've created a PR #73 with the updated models and updated the has_manual_speed and has_manual_duplex to reflect the new properties instead of calculating the regex themselves. 

I also created pytest based on the existing tests to check the values.  You may also want to mock up an interface with duplex half and speed 10 and speed 1000.

**Comment by mpenning** [comment]
This has been fixed in version 1.2.55
