### ISSUE TITLE
Support for aaa banners

### ISSUE THREAD

**Issue by Quadrai** [mpenning/ciscoconfparse#76]
Any chance to add support for aaa banners?
Following IOS configuration does currently not get parsed into parent/child objects.

```
aaa authentication fail-message ^C
#######################################################################
Incorrect Login
Legal Notice: Access to this device is restricted & all interactions are logged
#######################################################################
^C
```

**Comment by mpenning** [comment]
Apologies for the delay... may I ask how big of a deal this is?  I could cobble something together now, but it would be kindof ugly.  I have longer-term changes planned in the next year or so that would make handling this case much easier.

**Comment by mpenning** [comment]
This should be supported in 1.2.47, which is on pypi
