### ISSUE TITLE
req_cfgspec_all_diff method fails when using ignore_ws=True

### ISSUE THREAD

**Issue by bandrel** [mpenning/ciscoconfparse#77]
The _build_space_tolerant_regex method only accepts str input for the replacements.  The req_cfgspec_all_diff method accepts a list of strings.  A type error occurs if you set the ignore_ws=True

TypeError: expected string or buffer

**Comment by mpenning** [comment]
Thank you for finding this; it should be fixed in 1.2.47... the fix passes some basic unit tests.  Please test and let me know; if you find a problem, I'd like to see your specific use-case
