### ISSUE TITLE
There is no ScreenOS support

### ISSUE THREAD

**Issue by jdomag** [mpenning/ciscoconfparse#81]
I the project description there is a statement that CiscoConfParse supports Juniper ScreenOS devices. Screenos is not brace-delimited it's not possible to use junos model and i can't find any model matching screenos syntax.

**Comment by mpenning** [comment]
ScreenOS parses like Cisco IOS, but there is no syntax-specific parser for it.  Bottom line, it's incorrect to say that ciscoconfparse can't parse screenos.
