### ISSUE TITLE
Write support for JunOS

### ISSUE THREAD

**Issue by emilhf** [mpenning/ciscoconfparse#85]
Hey! Thanks for the excellent lib, we're using it at an ISP to transform router configs for a lab setup. However, being a heterogeneous network, we also need to handle JunOS configs. Is there a roadmap or any plans for making JunOS a first-class citizen? In particular we're looking for support for saving transformed configs, while still retaining the excellent search facilities. This is currently not possible due to the "IOS-style" trick via `syntax="junos"`

If there are any particular issues that  have been identified and need to be dealt with, I'd love to take a swing at them and perhaps submit a pull request.

**Comment by mpenning** [comment]
Your request is a bit unclear... I *think* you want the file saved brace-delimited, but I'm having to make an assumption.  To clarify, could you tell me what *exactly* is wrong with the file named "testme.txt" that I catted out below?

```
(py27_test) [mpenning@mudslide ciscoconfparse]$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ciscoconfparse import CiscoConfParse
>>> parse = CiscoConfParse('configs/sample_01.junos', syntax='junos')
>>> parse.save_as('testme.txt')
True
>>> quit()
(py27_test) [mpenning@mudslide ciscoconfparse]$ cat testme.txt
## Last commit: 2015-06-28 13:00:59 CST by mpenning
system
    host-name TEST01_EX
    domain-name pennington.net
    domain-search [ pennington.net lab.pennington.net ]
    location
        country-code 001
        building HQ_005
        floor 1
    root-authentication
        encrypted-password "$1$y7ArHxKU$zUbdeLfBirgkCsKiOJ5Qa0"; ## SECRET-DATA
    name-server
        172.16.3.222
    login
        announcement "Test Lab Switch"
        message "Unauthorized access is prohibited"
        user mpenning
            full-name "Mike Pennington"
            uid 1000
            class super-user
            authentication
                encrypted-password "$1$y7ArHxKU$zUbdeLfBirgkCsKiOJ5Qa0"; ## SECRET-DATA
    services
        ssh
            root-login allow
        telnet
        web-management
            http
    syslog
        user *
            any emergency
        file messages
            any notice
            authorization info
        file interactive-commands
            interactive-commands any
    ntp
        boot-server time.apple.com
        server 172.16.8.3
vlans
    Management
        vlan-id 1
        interface
            ge-0/0/0.0
            ge-0/0/1.0
            ge-0/0/2.0
            ge-0/0/3.0
    VLAN_FOO
        vlan-id 5
    vlan1
        vlan-id 1
        l3-interface vlan.1
    vlan800
        vlan-id 800
ethernet-switching-options
    storm-control
        interface all
interfaces
    ge-0/0/0
        unit 0
            family ethernet-switching
                port-mode access
                vlan
                    members VLAN_FOO
    ge-0/0/1
        unit 0
            family ethernet-switching
                port-mode trunk
                vlan
                    members all
                native-vlan-id 1
    vlan
        unit 0
            family inet
                address 172.16.15.5/22
routing-options
    static
        route 0.0.0.0/0 next-hop 172.16.12.1
        route 192.168.36.0/25 next-hop 172.16.12.1
(py27_test) [mpenning@mudslide ciscoconfparse]$
```

**Comment by Almujalled** [comment]
Hey! 
I am working with @emilhf  on this issue. Our ultimate goal is to be able to copy-paste Juniper configs that has been parsed and processed using this lib

**Comment by Almujalled** [comment]
Hi!
I am working with @emilhf on this issue. Our ultimate goal is to be able to copy-paste Juniper configs that has been parsed and processed using this lib through the JUNOS command  "load replace terminal"  I'll explain more using your example: 
```
root@GHAITH# load replace terminal                                        
[Type ^D at a new line to end input]
system
    host-name TEST01_EX
    domain-name pennington.net
    domain-search [ pennington.net lab.pennington.net ]
    location
        country-code 001
        building HQ_005
        floor 1
    root-authentication 
terminal:9:(23) syntax error: root-authentication
```
As you can see, I will get a syntax error since I don't have a brace-delimited config. So the brace-delimited config is a must. Therefore, we have been trying to parse the config file without the 
syntax='junos' argument to maintain the brace-delimited style. However, another issue rises that when an object is deleted. It seems like the delete method misses the last curly brace of an object. For example in the code below we are trying to delete the redundant routing engines from the "groups" configuration: 
The conf before parsing:
```
groups {
    re0 {
        system {
            host-name gw-re0;
        }
    }
    re1 {
        system {
            host-name gw-re1;
        }
    }  
```
The conf after:
```
groups {
    }  # Extra, unwanted curly brace
    }  # Extra, unwanted curly brace
```
Another example within the interfaces conf:
```
interfaces {
    apply-groups ignore-l3-incompletes;
    xe-0/0/0 {
        description "xxx";
        mtu 9192;
        unit 0 {
            description "xxxx";
            family inet {
                sampling {
                    input;
                }
                address xxxx;
            }
            family iso;
            family inet6 {
                sampling {
                    input;
                }
                address xxxx;
            }
            family mpls;
        }
    }
    inactive: xe-0/0/1 {
        description "xxxx";
        mtu 8950;
        unit 0 {
            family inet {
                address xxxx;
            }
            family iso;
            family inet6 {
                address xxxx;
            }
        }
    }
    xe-0/1/0 {
        description "xxxx";
        gigether-options {
            802.3ad ae0;
            ignore-l3-incompletes;
        }
        inactive: unit 0 {
            description "xxxx";
            family inet {
                filter {
                    input customer-filter-in;
                }
                sampling {
                    input;
                }
                address xxxx;
            }
            family inet6 {
                filter {
                    input customer-ipv6-filter-in;
                }
                sampling {
                    input;
                }
                address xxxx;
            }
        }
    }
```
After parsing, the xe-0/0/1 and  xe-0/1/0 are deleted using a Python script:
```
    for obj in parse.find_objects_w_child(r'..-\d\/\d\/\d', r'inactive'):
        obj.delete()
    for obj in parse.find_objects_w_parents(r'^\s*interfaces', r'inactive'):
        obj.delete()
```
So the output is: 
```
interfaces {
    apply-groups ignore-l3-incompletes;
    xe-0/0/0 {
        description "xxxx";
        #mtu 9192;
        unit 0 {
            description "xxxx";
            family inet {
                }
                address xxxx;
            }
            family iso;
            family inet6 {
                }
                address xxxx;
            }
            family mpls;
        }
    }
    } # Extra, unwanted curly brace
    } # Extra, unwanted curly brace
```

**Comment by jensenja** [comment]
Hi,

Not a contributor but I can't help but wonder if you're trying to use a square peg in a round hole.

What's preventing you from pulling the XML right out of the device and parsing it with python's `lxml` module or using something like `ncclient` to interact with your JunOS devices via NETCONF? CiscoConfParse's bread and butter is parsing whitespace-delimited configs that are common in Cisco/Brocade/probably other devices. With JunOS specifically, using `ncclient` or just dumping the whole config with a `| display xml` tacked on will essentially allow you to work with XML elements within a native Python datastructure before re-applying your config, ideally with NETCONF again. You're obviously free to work your implementation however you see fit, but transforming your configs with CiscoConfParse and then re-applying them to the device seems like you're doing too much work. No offense meant at all.

**Comment by superloopnetwork** [comment]
Hi there,

Amazing library you have created @mpenning. Really appreciate your hard work on this.

I'm facing the same issue as @emilhf  and @Almujalled. I totally understand their use case. The braces are required in order to do a 'load replace terminal'. Any way possible we are able to include them in the output?

**Comment by superloopnetwork** [comment]
I noticed you labeled as 'wontfix' now. Just curious, after we parse the junos configs and it outputs without the braces - is there a use case for those configs? Or it's strictly just for comparison (diff) since we are not able to input those parsed configs to junos.

**Comment by mpenning** [comment]
@superloopnetwork, there seems to be a misunderstanding.  This issue is not tagged "wontfix".

However, there are no plans for ciscoconfparse to do anything with brace-delimited configurations other than parsing and searching them.

**Comment by superloopnetwork** [comment]
Thanks for the clarification @mpenning . I'm trying to learn how to use it and maybe I'm doing something wrong - but I'm not understanding the output. There should be no diffs between the two as they are identical configs for both BASELINE and REQUIRED. But it's still showing me "corrections" via the 'no' commands.

>>> from ciscoconfparse import CiscoConfParse
>>> 
>>> BASELINE = """interfaces {
...     ge-0/0/0 {
...         unit 0 {
...             family ethernet-switching {
...                 port-mode access;
...                 vlan {
...                     members VLAN_FOO;
...                 }
...             }
...         }
...     }
... }""".splitlines()
>>> 
>>> REQUIRED = """interfaces {
...     ge-0/0/0 {
...         unit 0 {
...             family ethernet-switching {
...                 port-mode access;
...                 vlan {
...                     members VLAN_FOO;
...                 }
...             }
...         }
...     }
... }""".splitlines()
>>> 
>>> parse = CiscoConfParse(BASELINE, syntax='junos')
>>> 
>>> print '\n'.join(parse.sync_diff(REQUIRED, ''))
no interfaces 
    no ge-0/0/0 
        no unit 0 
            no family ethernet-switching 
                no port-mode access
                no vlan 
                    no members VLAN_FOO
interfaces {
    ge-0/0/0 {
        unit 0 {
            family ethernet-switching {
                port-mode access;
                vlan {
                    members VLAN_FOO;
                }
            }
        }
    }
}

**Comment by mpenning** [comment]
@superloopnetwork, if you really want diffs, you'll need to do something like this:

```python
parse = CiscoConfParse(BASELINE, syntax='junos')
diffs = parse.sync_diff(CiscoConfParse(REQUIRED, syntax='junos').ioscfg, '')
```

**Comment by superloopnetwork** [comment]
That's perfect @mpenning ! It worked. Thanks. But any way I can make it so that it can print all the way to the to level parent? For example the below vlan was changed but the output only shows one level of the parent 'vlan'.  Any way possible to include the interface?

```
>>> from ciscoconfparse import CiscoConfParse
>>> 
>>> BASELINE = """interfaces {
...     ge-0/0/0 {
...         unit 0 {
...             family ethernet-switching {
...                 port-mode access;
...                 vlan {
...                     members VLAN_FOO;
...                 }
...             }
...         }
...     }
... }""".splitlines()
>>> 
>>> REQUIRED = """interfaces {
...     ge-0/0/0 {
...         unit 0 {
...             family ethernet-switching {
...                 port-mode access;
...                 vlan {
...                     members VLAN_BAR;
...                 }
...             }
...         }
...     }
... }""".splitlines()
>>> 
>>> parse = CiscoConfParse(BASELINE, syntax='junos')
>>> diffs = parse.sync_diff(CiscoConfParse(REQUIRED, syntax='junos').ioscfg, '')
>>> for i in diffs:
...   print i
... 
                vlan 
                    no members VLAN_FOO
                vlan 
                    members VLAN_BAR
>>> 
```

**Comment by superloopnetwork** [comment]
.... kind bump...

**Comment by superloopnetwork** [comment]
Interesting enough if I were to change the syntax on the diff to 'ios', I get this output:
```
>>> parse = CiscoConfParse(BASELINE, syntax='junos')                          
>>> diffs = parse.sync_diff(CiscoConfParse(REQUIRED, syntax='ios').ioscfg, '')
>>> for i in diffs:
...   print(i)
... 
no interfaces
    no ge-0/0/0
        no unit 0
            no family ethernet-switching
                no port-mode access
                no vlan
                    no members VLAN_FOO
interfaces {
   ge-0/0/0 {
       unit 0 {
           family ethernet-switching {
               port-mode access;
               vlan {
                   members VLAN_BAR;
               }
           }
       }
   }
}
```
Which gives me the new config of what it should be but I wish It would be a "diff" similar to a "show | compare"... And the "no" statements doesn't retain the curly brackets...

**Comment by mpenning** [comment]
@superloopnetwork this issue was opened for JunOS write support.  I'm closing this issue.

Please open a new `parse.sync_diff()` issue if you want to ask for a change or submit a bug.  That said, I am not going to work on changes to `sync_diff()` soon; however, if you file a new ticket, I could look at that sometime in the future.
