### ISSUE TITLE
parsing access-list

### ISSUE THREAD

**Issue by ydave** [mpenning/ciscoconfparse#86]
I am trying to parse the access-list which has different types of statements as mentioned below. Curious is there a better way to utilise ciscoconfparse and create a dictionary?

10 permit tcp 20.2.2.2.0/18 any eq 22
20 permit tcp 10.20.0.0/18 eq ftp-data any gt 1023
30 permit udp 20.2.2.0/17 any eq snmp
40 permit tcp any gt 1024 any eq bgp
50 permit udp any 224.0.0.0/24 eq rip

Regards

**Comment by mpenning** [comment]
There are no shortcuts for ACLs in CiscoConfParse at this time.  I started trying to build it in, but it was just too much work.
