### ISSUE TITLE
When Importing CiscoConfParse into my script it attempts to open previous script

### ISSUE THREAD

**Issue by LongBeachHXC** [mpenning/ciscoconfparse#91]
Hey,

I am utilizing Windows Bash and am attempting to use this python library when I receive the following error. It appears to be trying to run a previous script that I do not want to use anymore. The ciscoconfparsetest.py is a new script I just built but for some reason my new script is trying to reference an old script I was testing with before. Some assistance would be greatly appreciated.

Thanks

forwein@LT-A0032856:/pythonscripts$ sudo python ciscoconfparsetest.py
sudo: unable to resolve host LT-A0032856
Traceback (most recent call last):
  File "ciscoconfparsetest.py", line 8, in <module>
    from ciscoconfparse import CiscoConfParse
  File "/pythonscripts/ciscoconfparse.py", line 56
    vlan123.append(obj)
          ^
SyntaxError: invalid syntax

**Comment by mpenning** [comment]
You have commited the classic blunder of naming a python script with the same name as the module it's importing.  Change the name of /pythonscripts/ciscoconfparse.py to something else.

**Comment by LongBeachHXC** [comment]
HAHAHAHA thanks mpenning...can yo you tell that I am a rookie? ;)
