### ISSUE TITLE
Save Results of the Parsed Search to File

### ISSUE THREAD

**Issue by LongBeachHXC** [mpenning/ciscoconfparse#92]
Hey,

I am having troubles figuring this out. Currently this is what I have:

for obj in parse.find_objects(r'123'):
    with open('interface_vlan_retrieval_test', 'w') as f:
        f.write(obj.text)
    print ('Config Test:', obj.text)

but with this I only get the last found object written to the file. I should have at least 15 ports populated but only see the last one. 

Thanks

**Comment by mpenning** [comment]
you are overwriting "interface_vlan_retrieval_test" every time you loop through obj in parse.find_objects('123').  Change your code to open the file *before* entering the loop...

**Comment by LongBeachHXC** [comment]
Oooo okay...I see what is happened. Gosh dayum...there is so much to learn :)
