### ISSUE TITLE
a non-cisco style indent makes nonsense parents/child relationships 

### ISSUE THREAD

**Issue by wuweiliang1** [mpenning/ciscoconfparse#93]
for example, let me show some configurations to you:
```
#
ip vpn-instance mgt_vrf
 route-distinguisher 2:1
#
 telnet server enable
 telnet server acl 2000
#
 switch-mode normal slot 0
 switch-mode normal slot 1
 switch-mode normal slot 2
 switch-mode normal slot 3
 switch-mode normal slot 4
 switch-mode normal slot 5
```

As we can see, with the second line indented with length 0, all others lines are indented with length 1, with comment character \# separating config block.
But with this kind of config, ciscoConfParse will consider the second line (with indent 0) as the parent config of all other lines, which is not  reasonable at all. when you try to retrieve the childrens node of
```
ip vpn-instance mgt_vrf
```
it will show you all the rest as its children.
The core loop of determining parents and children relationship is in the ciscoconfparse.py
```
            if (indent > 0) and not (parent is None):
                ## Add the line as a child (parent was cached)
                self._add_child_to_parent(retval, idx, indent, parent, obj)
            elif (indent > 0) and (parent is None):
                ## Walk backwards to find parent, and add the line as a child
                candidate_parent_index = idx - 1
                while candidate_parent_index >= 0:
                    candidate_parent = retval[candidate_parent_index]
                    if (candidate_parent.indent<indent) and \
                        candidate_parent.is_config_line:
                        # We found the parent
                        parent = candidate_parent
                        parents[indent] = parent  # Cache the parent
                        if indent == 0:
                            parent.oldest_ancestor = True
                        break
                    else:
                        candidate_parent_index -= 1
```
as you can see, no comment is checked in this loop, so it will cross the border of current config blocks.

**Comment by mpenning** [comment]
How did you get the original configuration with the indents shown?  CiscoConfParse doesn't know anything about that configuration and it is behaving as designed when it associates children with the parent in your example.  It doesn't matter if there are comments in the middle of the children, CiscoConfParse was designed to associate indented blocks below the parent as children.
