### ISSUE TITLE
Not getting output, please help. 

### ISSUE THREAD

**Issue by selvam33** [mpenning/ciscoconfparse#96]
from ciscoconfparse import CiscoConfParse

parse = CiscoConfParse(['C:\Users\ssamymuthux063973\Desktop\ciscoconfig.txt'])

rtr_interfaces = parse.find_objects("^interface")
print(parse)
print(rtr_interfaces)

Result:
<CiscoConfParse: 1 lines / syntax: ios / comment delimiter: '!' / factory: False>
[]

Process finished with exit code 0

**Comment by selvam33** [comment]
from ciscoconfparse import CiscoConfParse
import os

file = open('C:\Users\ssamymuthux063973\Desktop\ciscoconfig.txt')
text = file.read()
file.close()
parse = CiscoConfParse([text])
print(parse).

Result : "<CiscoConfParse: 1 lines / syntax: ios / comment delimiter: '!' / factory: False>"

I am able to read the file, but not getting after mentioning the text file in CiscoConfParse. Please help

**Comment by XenonR** [comment]
Please try to provide a list of lines to CiscoConfParse or the full filepath. Please reference 
http://www.pennington.net/py/ciscoconfparse/api_CiscoConfParse.html#ciscoconfparse.CiscoConfParse

At the moment you provide a list in a list with one listitem(the whole file).

Regards.

**Comment by selvam33** [comment]
Hi Xenon, 

Thanks, for your help.
